// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module im2col_2d_cl (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_V_address0,
        data_V_ce0,
        data_V_q0,
        data_col_V_address0,
        data_col_V_ce0,
        data_col_V_we0,
        data_col_V_d0,
        row,
        col
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] data_V_address0;
output   data_V_ce0;
input  [11:0] data_V_q0;
output  [4:0] data_col_V_address0;
output   data_col_V_ce0;
output   data_col_V_we0;
output  [11:0] data_col_V_d0;
input  [3:0] row;
input  [3:0] col;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_ce0;
reg[4:0] data_col_V_address0;
reg data_col_V_ce0;
reg data_col_V_we0;
reg[11:0] data_col_V_d0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] row_cast_fu_190_p1;
reg   [4:0] row_cast_reg_362;
wire   [4:0] col_cast_fu_194_p1;
reg   [4:0] col_cast_reg_367;
wire   [7:0] p_0106_rec_cast_cast_fu_198_p1;
reg   [7:0] p_0106_rec_cast_cast_reg_372;
wire    ap_CS_fsm_state2;
wire   [3:0] channel_1_fu_202_p2;
reg   [3:0] channel_1_reg_377;
wire   [3:0] p_rec_fu_214_p2;
reg   [3:0] p_rec_reg_385;
wire   [5:0] index_3_fu_220_p2;
reg   [5:0] index_3_reg_390;
wire   [0:0] tmp_fu_208_p2;
wire   [1:0] kernel_row_1_fu_236_p2;
reg   [1:0] kernel_row_1_reg_398;
wire    ap_CS_fsm_state3;
wire   [5:0] tmp_39_fu_247_p2;
reg   [5:0] tmp_39_reg_403;
wire   [0:0] tmp_s_fu_230_p2;
wire   [0:0] tmp_40_fu_253_p2;
reg   [0:0] tmp_40_reg_408;
wire   [11:0] tmp_41_fu_279_p2;
reg   [11:0] tmp_41_reg_412;
wire   [1:0] kernel_col_1_fu_295_p2;
reg   [1:0] kernel_col_1_reg_420;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_44_fu_306_p2;
reg   [0:0] tmp_44_reg_425;
wire   [0:0] tmp_42_fu_289_p2;
wire   [63:0] tmp_45_fu_312_p1;
reg   [63:0] tmp_45_reg_429;
wire   [11:0] sum_fu_342_p2;
reg   [11:0] sum_reg_434;
wire    ap_CS_fsm_state5;
wire   [5:0] index_4_fu_356_p2;
wire    ap_CS_fsm_state6;
reg   [3:0] p_0106_rec_reg_112;
reg   [5:0] index_reg_123;
reg   [3:0] channel_reg_135;
reg   [5:0] index_1_reg_146;
reg   [1:0] kernel_row_reg_157;
reg   [5:0] index_2_reg_168;
reg   [1:0] kernel_col_reg_179;
wire   [63:0] tmp_43_fu_347_p1;
wire   [63:0] sum_cast_fu_352_p1;
wire   [4:0] kernel_row_cast_fu_226_p1;
wire   [4:0] input_row_fu_242_p2;
wire   [8:0] p_shl9_fu_267_p3;
wire   [11:0] p_shl_fu_259_p3;
wire   [11:0] p_shl9_cast_fu_275_p1;
wire   [4:0] kernel_col_cast_fu_285_p1;
wire   [4:0] input_col_fu_301_p2;
wire   [3:0] tmp_36_fu_317_p1;
wire   [6:0] tmp_46_fu_321_p3;
wire   [7:0] tmp_79_cast_cast_cas_fu_329_p1;
wire   [7:0] tmp1_fu_333_p2;
wire   [11:0] tmp1_cast_fu_338_p1;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        channel_reg_135 <= channel_1_reg_377;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        channel_reg_135 <= 4'd8;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_42_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        index_1_reg_146 <= tmp_39_reg_403;
    end else if (((tmp_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        index_1_reg_146 <= index_reg_123;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        index_2_reg_168 <= index_4_fu_356_p2;
    end else if (((tmp_s_fu_230_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        index_2_reg_168 <= index_1_reg_146;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        index_reg_123 <= index_3_reg_390;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        index_reg_123 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kernel_col_reg_179 <= kernel_col_1_reg_420;
    end else if (((tmp_s_fu_230_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        kernel_col_reg_179 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_42_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_row_reg_157 <= kernel_row_1_reg_398;
    end else if (((tmp_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kernel_row_reg_157 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0106_rec_reg_112 <= p_rec_reg_385;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0106_rec_reg_112 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_1_reg_377 <= channel_1_fu_202_p2;
        p_0106_rec_cast_cast_reg_372[3 : 0] <= p_0106_rec_cast_cast_fu_198_p1[3 : 0];
        p_rec_reg_385 <= p_rec_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_cast_reg_367[3 : 0] <= col_cast_fu_194_p1[3 : 0];
        row_cast_reg_362[3 : 0] <= row_cast_fu_190_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        index_3_reg_390 <= index_3_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        kernel_col_1_reg_420 <= kernel_col_1_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_row_1_reg_398 <= kernel_row_1_fu_236_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_44_fu_306_p2 == 1'd1) & (tmp_42_fu_289_p2 == 1'd0) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum_reg_434 <= sum_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_230_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_39_reg_403 <= tmp_39_fu_247_p2;
        tmp_40_reg_408 <= tmp_40_fu_253_p2;
        tmp_41_reg_412[11 : 4] <= tmp_41_fu_279_p2[11 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_42_fu_289_p2 == 1'd0) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_44_reg_425 <= tmp_44_fu_306_p2;
        tmp_45_reg_429[5 : 0] <= tmp_45_fu_312_p1[5 : 0];
    end
end

always @ (*) begin
    if ((((tmp_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        data_V_ce0 = 1'b1;
    end else begin
        data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_col_V_address0 = tmp_45_reg_429;
    end else if (((tmp_40_reg_408 == 1'd1) & (tmp_42_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_col_V_address0 = tmp_43_fu_347_p1;
    end else if (((tmp_42_fu_289_p2 == 1'd0) & (tmp_44_fu_306_p2 == 1'd0) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_col_V_address0 = tmp_45_fu_312_p1;
    end else begin
        data_col_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((tmp_42_fu_289_p2 == 1'd0) & (tmp_44_fu_306_p2 == 1'd0) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_40_reg_408 == 1'd1) & (tmp_42_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        data_col_V_ce0 = 1'b1;
    end else begin
        data_col_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_col_V_d0 = data_V_q0;
    end else if ((((tmp_42_fu_289_p2 == 1'd0) & (tmp_44_fu_306_p2 == 1'd0) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_40_reg_408 == 1'd1) & (tmp_42_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        data_col_V_d0 = 12'd0;
    end else begin
        data_col_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_44_reg_425 == 1'd1) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((tmp_42_fu_289_p2 == 1'd0) & (tmp_44_fu_306_p2 == 1'd0) & (tmp_40_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_40_reg_408 == 1'd1) & (tmp_42_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        data_col_V_we0 = 1'b1;
    end else begin
        data_col_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_s_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((tmp_42_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b1 == ap_CS_fsm_state4) & (((tmp_40_reg_408 == 1'd1) & (tmp_42_fu_289_p2 == 1'd0)) | ((tmp_42_fu_289_p2 == 1'd0) & (tmp_44_fu_306_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign channel_1_fu_202_p2 = ($signed(channel_reg_135) + $signed(4'd15));

assign col_cast_fu_194_p1 = col;

assign data_V_address0 = sum_cast_fu_352_p1;

assign index_3_fu_220_p2 = (index_reg_123 + 6'd4);

assign index_4_fu_356_p2 = (index_2_reg_168 + 6'd1);

assign input_col_fu_301_p2 = (col_cast_reg_367 + kernel_col_cast_fu_285_p1);

assign input_row_fu_242_p2 = (kernel_row_cast_fu_226_p1 + row_cast_reg_362);

assign kernel_col_1_fu_295_p2 = (kernel_col_reg_179 + 2'd1);

assign kernel_col_cast_fu_285_p1 = kernel_col_reg_179;

assign kernel_row_1_fu_236_p2 = (kernel_row_reg_157 + 2'd1);

assign kernel_row_cast_fu_226_p1 = kernel_row_reg_157;

assign p_0106_rec_cast_cast_fu_198_p1 = p_0106_rec_reg_112;

assign p_rec_fu_214_p2 = (p_0106_rec_reg_112 + 4'd1);

assign p_shl9_cast_fu_275_p1 = p_shl9_fu_267_p3;

assign p_shl9_fu_267_p3 = {{input_row_fu_242_p2}, {4'd0}};

assign p_shl_fu_259_p3 = {{input_row_fu_242_p2}, {7'd0}};

assign row_cast_fu_190_p1 = row;

assign sum_cast_fu_352_p1 = sum_reg_434;

assign sum_fu_342_p2 = (tmp_41_reg_412 + tmp1_cast_fu_338_p1);

assign tmp1_cast_fu_338_p1 = tmp1_fu_333_p2;

assign tmp1_fu_333_p2 = (p_0106_rec_cast_cast_reg_372 + tmp_79_cast_cast_cas_fu_329_p1);

assign tmp_36_fu_317_p1 = input_col_fu_301_p2[3:0];

assign tmp_39_fu_247_p2 = (index_1_reg_146 + 6'd2);

assign tmp_40_fu_253_p2 = ((input_row_fu_242_p2 > 5'd13) ? 1'b1 : 1'b0);

assign tmp_41_fu_279_p2 = (p_shl_fu_259_p3 - p_shl9_cast_fu_275_p1);

assign tmp_42_fu_289_p2 = ((kernel_col_reg_179 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_43_fu_347_p1 = index_2_reg_168;

assign tmp_44_fu_306_p2 = ((input_col_fu_301_p2 < 5'd14) ? 1'b1 : 1'b0);

assign tmp_45_fu_312_p1 = index_2_reg_168;

assign tmp_46_fu_321_p3 = {{tmp_36_fu_317_p1}, {3'd0}};

assign tmp_79_cast_cast_cas_fu_329_p1 = tmp_46_fu_321_p3;

assign tmp_fu_208_p2 = ((channel_reg_135 == 4'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_230_p2 = ((kernel_row_reg_157 == 2'd2) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    row_cast_reg_362[4] <= 1'b0;
    col_cast_reg_367[4] <= 1'b0;
    p_0106_rec_cast_cast_reg_372[7:4] <= 4'b0000;
    tmp_41_reg_412[3:0] <= 4'b0000;
    tmp_45_reg_429[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //im2col_2d_cl
