#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul  1 15:05:57 2020

@author: filipe
"""


from tensorflow.keras.utils import to_categorical
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd


import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l1
from callbacks import all_callbacks
from tensorflow.keras.layers import Activation, MaxPooling2D, Flatten, Conv2D, Dense


import hls4ml
import xmltodict


import numpy as np
import random
import keras
from sklearn.metrics import accuracy_score
from keras import backend as K

import shutil
import os

def change_precision(x,y):
    default_precision = 'ap_fixed<'+ str(x) +','+str(y)+',AP_RND,AP_SAT>'
    return default_precision


def reset_weights(model):
  for layer in model.layers: 
    if isinstance(layer, tf.keras.Model):
      reset_weights(layer)
      continue
    for k, initializer in layer.__dict__.items():
      if "initializer" not in k:
        continue
      # find the corresponding variable
      var = getattr(layer, k.replace("_initializer", ""))
      var.assign(initializer(var.shape, var.dtype))
     
        

##pre processing
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

Y_train1 = train[['label']]
X_train1 = train.drop(train.columns[[0]], axis=1)
X_test1 = test


X_train1 = np.array(X_train1)
X_test1 = np.array(X_test1)

#Reshape the training and test set
X_train1 = X_train1.reshape(X_train1.shape[0], 28, 28, 1)/255
X_test1 = X_test1.reshape(X_test1.shape[0], 28, 28, 1)/255

#Padding the images by 2 pixels since in the paper input images were 32x32
X_train1 = np.pad(X_train1, ((0,0),(2,2),(2,2),(0,0)), 'constant')
X_test1 = np.pad(X_test1, ((0,0),(2,2),(2,2),(0,0)), 'constant')

X_train, X_test, Y_train, Y_test = train_test_split(X_train1, Y_train1, test_size=0.25, random_state=42)

#Standardization
mean_px = X_train.mean().astype(np.float32)
std_px = X_train.std().astype(np.float32)
X_train = (X_train - mean_px)/(std_px)

#One-hot encoding the labels
Y_train = to_categorical(Y_train)

print(X_train.shape[0], "train samples")
print(X_test.shape[0], "test samples")

# how many points in graph? x points
DISCRETE_OS_SIZE = 8

# create matrix x*y

q_table = np.random.uniform(low=-1, high=1, size=(DISCRETE_OS_SIZE, 6))

LEARNING_RATE = 0.1

DISCOUNT = 0.95
EPISODES = 10


resource_usage_obj = 2
accuracy_obj = 0.8

resource = 2
accuracy = 0


dic_usage = [0, 0, 0, 0]
dic_tested = []
data = []


path = '/home/filipe/MEGA/GitHub/hls4ml-tutorial-master/model_z/'
   
num_model_path = '0' + '/'
model_path = os.path.join(path, num_model_path)
if (not os.path.isdir(model_path)):
    os.makedirs(model_path)

model = Sequential()

model.add(Conv2D(8, (4, 4), strides=(1,1), input_shape=(32,32, 1), name="conv2d_0_m"))

model.add(Activation(activation='relu', name='relu1'))
model.add(MaxPooling2D(pool_size = (2,2), strides = (2,2), name='max1'))

model.add(Conv2D(
    16, (2, 2), strides=(1,1),
    name="conv2d_1_m"))

model.add(Activation(activation='relu', name='relu2'))
model.add(MaxPooling2D(pool_size = (2,2), strides = (2,2), name='max2'))
model.add(Flatten())
model.add(Dense(120, name='fc1',
                 kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='relu', name='relu3'))
model.add(Dense(84, name='fc2',
                 kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='relu', name='relu4'))
model.add(Dense(10, name='output',
                 kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='softmax', name='softmax'))


train = True

if train:
    adam = Adam(lr=0.0001)
 
    model.compile(optimizer=adam, loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])
    callbacks = all_callbacks(stop_patience = 1000,
                              lr_factor = 0.5,
                              lr_patience = 10,
                              lr_epsilon = 0.000001,
                              lr_cooldown = 2,
                              lr_minimum = 0.0000001,
                              outputDir = model_path)
 #   callbacks.callbacks.append(pruning_callbacks.UpdatePruningStep())
    model.fit(X_train, Y_train, batch_size=1024,
              epochs=1, validation_split=0.25, shuffle=True, callbacks = callbacks.callbacks)

X = 15
Y = 6

print("DATA size: ")   
print(X,Y)
precision = change_precision(X,Y)
#
print(precision)
config = hls4ml.utils.config_from_keras_model(model, granularity='model', default_precision=precision)
config['Model']['ReuseFactor'] = 2000
print(config)

hls_model_path = os.path.join(model_path, 'hls4ml_prj/')
if (not os.path.isdir(model_path)):
    os.makedirs(hls_model_path)

hls_model = hls4ml.converters.convert_from_keras_model(model, hls_config=config, output_dir=hls_model_path)
hls_model.compile()

print("Evaluating...")
accuracy = 0
z = np.argmax(hls_model.predict(X_test), axis=1)
accuracy = accuracy_score(Y_test, z)
print("{}".format(accuracy))
data.append(accuracy)





num_model_path = '1' + '/'
model_path = os.path.join(path, num_model_path)
if (not os.path.isdir(model_path)):
    os.makedirs(model_path)

model1 = Sequential()

model1.add(Conv2D(8, (4, 4), strides=(1,1), input_shape=(32,32, 1), name="conv2d_0_m"))

model1.add(Activation(activation='relu', name='relu1'))
model1.add(MaxPooling2D(pool_size = (2,2), strides = (2,2), name='max1'))

model1.add(Conv2D(
    16, (2, 2), strides=(1,1),
    name="conv2d_1_m"))

model1.add(Activation(activation='relu', name='relu2'))
model1.add(MaxPooling2D(pool_size = (2,2), strides = (2,2), name='max2'))
model1.add(Flatten())
model1.add(Dense(120, name='fc1',
                 kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model1.add(Activation(activation='relu', name='relu3'))
model1.add(Dense(84, name='fc2',
                 kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model1.add(Activation(activation='relu', name='relu4'))
model1.add(Dense(10, name='output',
                 kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model1.add(Activation(activation='softmax', name='softmax'))


train = True

if train:
    adam = Adam(lr=0.0001)
 
    model1.compile(optimizer=adam, loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])
    callbacks = all_callbacks(stop_patience = 1000,
                              lr_factor = 0.5,
                              lr_patience = 10,
                              lr_epsilon = 0.000001,
                              lr_cooldown = 2,
                              lr_minimum = 0.0000001,
                              outputDir = model_path)
 #   callbacks.callbacks.append(pruning_callbacks.UpdatePruningStep())
    model1.fit(X_train, Y_train, batch_size=1024,
              epochs=1, validation_split=0.25, shuffle=True, callbacks = callbacks.callbacks)

X = 13
Y = 3

print("DATA size: ")   
print(X,Y)
precision = change_precision(X,Y)
#
print(precision)
config = hls4ml.utils.config_from_keras_model(model1, granularity='model', default_precision=precision)
config['Model']['ReuseFactor'] = 2000
print(config)

hls_model_path = os.path.join(model_path, 'hls4ml_prj/')
if (not os.path.isdir(model_path)):
    os.makedirs(hls_model_path)

hls_model1 = hls4ml.converters.convert_from_keras_model(model1, hls_config=config, output_dir=hls_model_path)
hls_model1.compile()

print("Evaluating...")
accuracy = 0
z = np.argmax(hls_model1.predict(X_test), axis=1)
accuracy = accuracy_score(Y_test, z)
print("{}".format(accuracy))
data.append(accuracy)
 

 
