// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_large_rf_gt_ni_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_V_address0,
        data_V_ce0,
        data_V_q0,
        res_V_address0,
        res_V_ce0,
        res_V_we0,
        res_V_d0
);

parameter    ap_ST_fsm_state1 = 35'd1;
parameter    ap_ST_fsm_state2 = 35'd2;
parameter    ap_ST_fsm_state3 = 35'd4;
parameter    ap_ST_fsm_state4 = 35'd8;
parameter    ap_ST_fsm_state5 = 35'd16;
parameter    ap_ST_fsm_state6 = 35'd32;
parameter    ap_ST_fsm_state7 = 35'd64;
parameter    ap_ST_fsm_state8 = 35'd128;
parameter    ap_ST_fsm_state9 = 35'd256;
parameter    ap_ST_fsm_state10 = 35'd512;
parameter    ap_ST_fsm_state11 = 35'd1024;
parameter    ap_ST_fsm_state12 = 35'd2048;
parameter    ap_ST_fsm_state13 = 35'd4096;
parameter    ap_ST_fsm_state14 = 35'd8192;
parameter    ap_ST_fsm_state15 = 35'd16384;
parameter    ap_ST_fsm_state16 = 35'd32768;
parameter    ap_ST_fsm_state17 = 35'd65536;
parameter    ap_ST_fsm_state18 = 35'd131072;
parameter    ap_ST_fsm_state19 = 35'd262144;
parameter    ap_ST_fsm_state20 = 35'd524288;
parameter    ap_ST_fsm_state21 = 35'd1048576;
parameter    ap_ST_fsm_state22 = 35'd2097152;
parameter    ap_ST_fsm_state23 = 35'd4194304;
parameter    ap_ST_fsm_state24 = 35'd8388608;
parameter    ap_ST_fsm_state25 = 35'd16777216;
parameter    ap_ST_fsm_state26 = 35'd33554432;
parameter    ap_ST_fsm_state27 = 35'd67108864;
parameter    ap_ST_fsm_state28 = 35'd134217728;
parameter    ap_ST_fsm_state29 = 35'd268435456;
parameter    ap_ST_fsm_state30 = 35'd536870912;
parameter    ap_ST_fsm_state31 = 35'd1073741824;
parameter    ap_ST_fsm_state32 = 35'd2147483648;
parameter    ap_ST_fsm_state33 = 35'd4294967296;
parameter    ap_ST_fsm_state34 = 35'd8589934592;
parameter    ap_ST_fsm_state35 = 35'd17179869184;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] data_V_address0;
output   data_V_ce0;
input  [12:0] data_V_q0;
output  [6:0] res_V_address0;
output   res_V_ce0;
output   res_V_we0;
output  [13:0] res_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_ce0;
reg res_V_ce0;
reg res_V_we0;

(* fsm_encoding = "none" *) reg   [34:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] outidx4_address0;
reg    outidx4_ce0;
wire   [5:0] outidx4_q0;
wire   [12:0] w14_V_address0;
reg    w14_V_ce0;
wire   [24:0] w14_V_q0;
wire   [13:0] acc_V_q0;
reg  signed [13:0] reg_269;
wire    ap_CS_fsm_state28;
wire    grp_product_fu_263_ap_ready;
wire    grp_product_fu_263_ap_done;
wire    ap_CS_fsm_state34;
wire   [6:0] iacc_2_fu_280_p2;
wire    ap_CS_fsm_state2;
wire   [13:0] w_index_cast_fu_291_p1;
reg   [13:0] w_index_cast_reg_550;
wire    ap_CS_fsm_state3;
wire   [12:0] ir_fu_301_p2;
reg   [12:0] ir_reg_558;
wire   [0:0] exitcond_fu_295_p2;
reg   [5:0] out_index_reg_568;
wire    ap_CS_fsm_state4;
wire   [6:0] out_index_cast_fu_317_p1;
wire    ap_CS_fsm_state5;
wire   [13:0] extLd_fu_320_p1;
reg   [13:0] extLd_reg_583;
wire   [0:0] tmp_45_fu_324_p3;
reg   [0:0] tmp_45_reg_588;
wire    ap_CS_fsm_state6;
wire   [1:0] im_2_fu_332_p2;
reg   [1:0] im_2_reg_592;
wire    ap_CS_fsm_state22;
wire   [13:0] grp_fu_338_p2;
reg   [13:0] tmp_30_reg_602;
wire    ap_CS_fsm_state23;
wire   [29:0] grp_fu_535_p2;
reg   [29:0] mul_reg_607;
wire    ap_CS_fsm_state24;
reg   [0:0] tmp_46_reg_617;
reg   [24:0] w14_V_load_reg_622;
wire    ap_CS_fsm_state25;
wire   [4:0] tmp_49_fu_387_p2;
reg   [4:0] tmp_49_reg_627;
wire   [13:0] tmp_52_fu_405_p1;
reg   [13:0] tmp_52_reg_632;
wire    ap_CS_fsm_state26;
reg   [6:0] acc_V_addr_4_reg_637;
wire    ap_CS_fsm_state27;
wire   [13:0] grp_product_fu_263_ap_return;
reg  signed [13:0] p_Val2_14_reg_642;
reg   [0:0] p_Result_s_reg_648;
wire    ap_CS_fsm_state29;
wire   [13:0] p_Val2_16_fu_435_p2;
reg   [13:0] p_Val2_16_reg_655;
reg   [0:0] p_Result_10_reg_660;
wire   [0:0] overflow_fu_453_p2;
reg   [0:0] overflow_reg_667;
wire    ap_CS_fsm_state30;
wire   [0:0] underflow_fu_463_p2;
reg   [0:0] underflow_reg_671;
wire   [0:0] brmerge9_fu_468_p2;
reg   [0:0] brmerge9_reg_675;
wire   [13:0] w_index_4_cast_fu_482_p2;
wire    ap_CS_fsm_state31;
wire   [6:0] out_index_4_fu_494_p2;
wire   [0:0] tmp_59_fu_488_p2;
wire   [31:0] in_index_2_fu_500_p2;
reg   [31:0] in_index_2_reg_692;
wire   [31:0] p_s_fu_511_p3;
wire    ap_CS_fsm_state32;
wire   [6:0] ires_2_fu_524_p2;
reg   [6:0] ires_2_reg_706;
wire    ap_CS_fsm_state33;
wire   [63:0] tmp_56_fu_530_p1;
reg   [63:0] tmp_56_reg_711;
wire   [0:0] tmp_55_fu_518_p2;
reg   [6:0] acc_V_address0;
reg    acc_V_ce0;
reg    acc_V_we0;
reg   [13:0] acc_V_d0;
wire    grp_product_fu_263_ap_start;
wire    grp_product_fu_263_ap_idle;
reg   [6:0] iacc_reg_187;
wire   [0:0] exitcond7_fu_274_p2;
reg   [12:0] w_index_reg_198;
reg  signed [31:0] in_index_reg_209;
reg   [1:0] im_reg_221;
reg   [6:0] out_index7_reg_232;
reg   [13:0] w_index7_reg_242;
reg   [6:0] ires_reg_252;
wire    ap_CS_fsm_state35;
reg    grp_product_fu_263_ap_start_reg;
wire   [63:0] tmp_fu_286_p1;
wire   [63:0] tmp_s_fu_307_p1;
wire  signed [63:0] tmp_54_fu_312_p1;
wire   [63:0] tmp_32_fu_348_p1;
wire   [63:0] tmp_57_fu_409_p1;
wire   [1:0] tmp_6_fu_359_p4;
wire   [2:0] p_shl8_fu_368_p3;
wire   [4:0] tmp_47_fu_376_p3;
wire   [4:0] tmp_48_fu_383_p1;
wire  signed [27:0] w14_V_load_cast_fu_393_p1;
wire   [27:0] tmp_50_fu_396_p1;
wire   [27:0] tmp_51_fu_399_p2;
wire  signed [14:0] lhs_V_fu_414_p1;
wire  signed [14:0] rhs_V_fu_418_p1;
wire   [14:0] ret_V_fu_421_p2;
wire   [0:0] tmp_21_fu_448_p2;
wire   [0:0] tmp_58_fu_458_p2;
wire   [14:0] w_index7_cast_fu_472_p1;
wire   [14:0] w_index_2_fu_476_p2;
wire   [0:0] tmp_60_fu_506_p2;
wire   [13:0] grp_fu_535_p0;
wire   [15:0] grp_fu_535_p1;
reg    grp_fu_338_ap_start;
wire    grp_fu_338_ap_done;
reg   [34:0] ap_NS_fsm;
wire   [29:0] grp_fu_535_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 35'd1;
#0 grp_product_fu_263_ap_start_reg = 1'b0;
end

dense_large_rf_gt_ni_3_outidx4 #(
    .DataWidth( 6 ),
    .AddressRange( 5040 ),
    .AddressWidth( 13 ))
outidx4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx4_address0),
    .ce0(outidx4_ce0),
    .q0(outidx4_q0)
);

dense_large_rf_gt_ni_3_w14_V #(
    .DataWidth( 25 ),
    .AddressRange( 5040 ),
    .AddressWidth( 13 ))
w14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w14_V_address0),
    .ce0(w14_V_ce0),
    .q0(w14_V_q0)
);

dense_large_rf_gt_ni_3_acc_V #(
    .DataWidth( 14 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
acc_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(acc_V_address0),
    .ce0(acc_V_ce0),
    .we0(acc_V_we0),
    .d0(acc_V_d0),
    .q0(acc_V_q0)
);

product grp_product_fu_263(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_product_fu_263_ap_start),
    .ap_done(grp_product_fu_263_ap_done),
    .ap_idle(grp_product_fu_263_ap_idle),
    .ap_ready(grp_product_fu_263_ap_ready),
    .a_V(extLd_reg_583),
    .w_V(tmp_52_reg_632),
    .ap_return(grp_product_fu_263_ap_return)
);

myproject_urem_14ns_14ns_14_18_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 18 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_urem_14ns_14ns_14_18_seq_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_338_ap_start),
    .done(grp_fu_338_ap_done),
    .din0(w_index7_reg_242),
    .din1(14'd5040),
    .ce(1'b1),
    .dout(grp_fu_338_p2)
);

myproject_mul_mul_14ns_16ns_30_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
myproject_mul_mul_14ns_16ns_30_3_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_535_p0),
    .din1(grp_fu_535_p1),
    .ce(1'b1),
    .dout(grp_fu_535_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_product_fu_263_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state27)) begin
            grp_product_fu_263_ap_start_reg <= 1'b1;
        end else if ((grp_product_fu_263_ap_ready == 1'b1)) begin
            grp_product_fu_263_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iacc_reg_187 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond7_fu_274_p2 == 1'd0))) begin
        iacc_reg_187 <= iacc_2_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (tmp_59_fu_488_p2 == 1'd0) & (tmp_45_reg_588 == 1'd0))) begin
        im_reg_221 <= im_2_reg_592;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        im_reg_221 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond7_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_index_reg_209 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        in_index_reg_209 <= p_s_fu_511_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_295_p2 == 1'd1))) begin
        ires_reg_252 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        ires_reg_252 <= ires_2_reg_706;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (tmp_59_fu_488_p2 == 1'd0) & (tmp_45_reg_588 == 1'd0))) begin
        out_index7_reg_232 <= out_index_4_fu_494_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        out_index7_reg_232 <= out_index_cast_fu_317_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (tmp_59_fu_488_p2 == 1'd0) & (tmp_45_reg_588 == 1'd0))) begin
        w_index7_reg_242 <= w_index_4_cast_fu_482_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        w_index7_reg_242 <= w_index_cast_reg_550;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond7_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        w_index_reg_198 <= 13'd0;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        w_index_reg_198 <= ir_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        acc_V_addr_4_reg_637 <= tmp_57_fu_409_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        brmerge9_reg_675 <= brmerge9_fu_468_p2;
        overflow_reg_667 <= overflow_fu_453_p2;
        underflow_reg_671 <= underflow_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        extLd_reg_583[12 : 0] <= extLd_fu_320_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        im_2_reg_592 <= im_2_fu_332_p2;
        tmp_45_reg_588 <= im_reg_221[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & ((tmp_59_fu_488_p2 == 1'd1) | (tmp_45_reg_588 == 1'd1)))) begin
        in_index_2_reg_692 <= in_index_2_fu_500_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ir_reg_558 <= ir_fu_301_p2;
        w_index_cast_reg_550[12 : 0] <= w_index_cast_fu_291_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        ires_2_reg_706 <= ires_2_fu_524_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        mul_reg_607 <= grp_fu_535_p2;
        tmp_46_reg_617 <= grp_fu_535_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_index_reg_568 <= outidx4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        p_Result_10_reg_660 <= p_Val2_16_fu_435_p2[32'd13];
        p_Result_s_reg_648 <= ret_V_fu_421_p2[32'd14];
        p_Val2_16_reg_655 <= p_Val2_16_fu_435_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_product_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        p_Val2_14_reg_642 <= grp_product_fu_263_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state34) | ((grp_product_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28)))) begin
        reg_269 <= acc_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        tmp_30_reg_602 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        tmp_49_reg_627[4 : 1] <= tmp_49_fu_387_p2[4 : 1];
        w14_V_load_reg_622 <= w14_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        tmp_52_reg_632 <= tmp_52_fu_405_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state33) & (tmp_55_fu_518_p2 == 1'd0))) begin
        tmp_56_reg_711[6 : 0] <= tmp_56_fu_530_p1[6 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        acc_V_address0 = tmp_56_fu_530_p1;
    end else if (((1'b1 == ap_CS_fsm_state30) | ((brmerge9_reg_675 == 1'd1) & (overflow_reg_667 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (tmp_45_reg_588 == 1'd0)) | ((brmerge9_reg_675 == 1'd1) & (underflow_reg_671 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (overflow_reg_667 == 1'd0) & (tmp_45_reg_588 == 1'd0)))) begin
        acc_V_address0 = acc_V_addr_4_reg_637;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        acc_V_address0 = tmp_57_fu_409_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        acc_V_address0 = tmp_fu_286_p1;
    end else begin
        acc_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state2) | ((brmerge9_reg_675 == 1'd1) & (overflow_reg_667 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (tmp_45_reg_588 == 1'd0)) | ((brmerge9_reg_675 == 1'd1) & (underflow_reg_671 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (overflow_reg_667 == 1'd0) & (tmp_45_reg_588 == 1'd0)))) begin
        acc_V_ce0 = 1'b1;
    end else begin
        acc_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((brmerge9_reg_675 == 1'd1) & (overflow_reg_667 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (tmp_45_reg_588 == 1'd0))) begin
        acc_V_d0 = 14'd8191;
    end else if (((brmerge9_reg_675 == 1'd1) & (underflow_reg_671 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (overflow_reg_667 == 1'd0) & (tmp_45_reg_588 == 1'd0))) begin
        acc_V_d0 = 14'd8192;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        acc_V_d0 = p_Val2_16_reg_655;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        acc_V_d0 = 14'd0;
    end else begin
        acc_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | ((brmerge9_reg_675 == 1'd1) & (overflow_reg_667 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (tmp_45_reg_588 == 1'd0)) | ((brmerge9_reg_675 == 1'd1) & (underflow_reg_671 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (overflow_reg_667 == 1'd0) & (tmp_45_reg_588 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (exitcond7_fu_274_p2 == 1'd0)))) begin
        acc_V_we0 = 1'b1;
    end else begin
        acc_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_55_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state33)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_55_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_V_ce0 = 1'b1;
    end else begin
        data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_45_fu_324_p3 == 1'd0))) begin
        grp_fu_338_ap_start = 1'b1;
    end else begin
        grp_fu_338_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        outidx4_ce0 = 1'b1;
    end else begin
        outidx4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        res_V_ce0 = 1'b1;
    end else begin
        res_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        res_V_we0 = 1'b1;
    end else begin
        res_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        w14_V_ce0 = 1'b1;
    end else begin
        w14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond7_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_295_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (tmp_45_fu_324_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((grp_product_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b1 == ap_CS_fsm_state31) & (tmp_59_fu_488_p2 == 1'd0) & (tmp_45_reg_588 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state33 : begin
            if (((tmp_55_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign brmerge9_fu_468_p2 = (p_Result_s_reg_648 ^ p_Result_10_reg_660);

assign data_V_address0 = tmp_54_fu_312_p1;

assign exitcond7_fu_274_p2 = ((iacc_reg_187 == 7'd84) ? 1'b1 : 1'b0);

assign exitcond_fu_295_p2 = ((w_index_reg_198 == 13'd5040) ? 1'b1 : 1'b0);

assign extLd_fu_320_p1 = data_V_q0;

assign grp_fu_535_p0 = grp_fu_535_p00;

assign grp_fu_535_p00 = w_index7_reg_242;

assign grp_fu_535_p1 = 30'd26631;

assign grp_product_fu_263_ap_start = grp_product_fu_263_ap_start_reg;

assign iacc_2_fu_280_p2 = (iacc_reg_187 + 7'd1);

assign im_2_fu_332_p2 = (im_reg_221 + 2'd1);

assign in_index_2_fu_500_p2 = ($signed(in_index_reg_209) + $signed(32'd1));

assign ir_fu_301_p2 = (w_index_reg_198 + 13'd1);

assign ires_2_fu_524_p2 = (ires_reg_252 + 7'd1);

assign lhs_V_fu_414_p1 = reg_269;

assign out_index_4_fu_494_p2 = (out_index7_reg_232 + 7'd42);

assign out_index_cast_fu_317_p1 = out_index_reg_568;

assign outidx4_address0 = tmp_s_fu_307_p1;

assign overflow_fu_453_p2 = (tmp_21_fu_448_p2 & p_Result_10_reg_660);

assign p_Val2_16_fu_435_p2 = ($signed(reg_269) + $signed(p_Val2_14_reg_642));

assign p_s_fu_511_p3 = ((tmp_60_fu_506_p2[0:0] === 1'b1) ? 32'd0 : in_index_2_reg_692);

assign p_shl8_fu_368_p3 = {{tmp_6_fu_359_p4}, {1'd0}};

assign res_V_address0 = tmp_56_reg_711;

assign res_V_d0 = reg_269;

assign ret_V_fu_421_p2 = ($signed(lhs_V_fu_414_p1) + $signed(rhs_V_fu_418_p1));

assign rhs_V_fu_418_p1 = p_Val2_14_reg_642;

assign tmp_21_fu_448_p2 = (p_Result_s_reg_648 ^ 1'd1);

assign tmp_32_fu_348_p1 = tmp_30_reg_602;

assign tmp_45_fu_324_p3 = im_reg_221[32'd1];

assign tmp_47_fu_376_p3 = {{tmp_46_reg_617}, {4'd0}};

assign tmp_48_fu_383_p1 = p_shl8_fu_368_p3;

assign tmp_49_fu_387_p2 = (tmp_47_fu_376_p3 - tmp_48_fu_383_p1);

assign tmp_50_fu_396_p1 = tmp_49_reg_627;

assign tmp_51_fu_399_p2 = w14_V_load_cast_fu_393_p1 >> tmp_50_fu_396_p1;

assign tmp_52_fu_405_p1 = tmp_51_fu_399_p2[13:0];

assign tmp_54_fu_312_p1 = in_index_reg_209;

assign tmp_55_fu_518_p2 = ((ires_reg_252 == 7'd84) ? 1'b1 : 1'b0);

assign tmp_56_fu_530_p1 = ires_reg_252;

assign tmp_57_fu_409_p1 = out_index7_reg_232;

assign tmp_58_fu_458_p2 = (p_Result_10_reg_660 ^ 1'd1);

assign tmp_59_fu_488_p2 = ((w_index_2_fu_476_p2 > 15'd10079) ? 1'b1 : 1'b0);

assign tmp_60_fu_506_p2 = (($signed(in_index_2_reg_692) > $signed(32'd119)) ? 1'b1 : 1'b0);

assign tmp_6_fu_359_p4 = {{mul_reg_607[28:27]}};

assign tmp_fu_286_p1 = iacc_reg_187;

assign tmp_s_fu_307_p1 = w_index_reg_198;

assign underflow_fu_463_p2 = (tmp_58_fu_458_p2 & p_Result_s_reg_648);

assign w14_V_address0 = tmp_32_fu_348_p1;

assign w14_V_load_cast_fu_393_p1 = $signed(w14_V_load_reg_622);

assign w_index7_cast_fu_472_p1 = w_index7_reg_242;

assign w_index_2_fu_476_p2 = (w_index7_cast_fu_472_p1 + 15'd5040);

assign w_index_4_cast_fu_482_p2 = (w_index7_reg_242 + 14'd5040);

assign w_index_cast_fu_291_p1 = w_index_reg_198;

always @ (posedge ap_clk) begin
    w_index_cast_reg_550[13] <= 1'b0;
    extLd_reg_583[13] <= 1'b0;
    tmp_49_reg_627[0] <= 1'b0;
    tmp_56_reg_711[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //dense_large_rf_gt_ni_3
