// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pooling2d_cl_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_address0,
        data_V_ce0,
        data_V_q0,
        res_V_address0,
        res_V_ce0,
        res_V_we0,
        res_V_d0
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [11:0] data_V_address0;
output   data_V_ce0;
input  [12:0] data_V_q0;
output  [9:0] res_V_address0;
output   res_V_ce0;
output   res_V_we0;
output  [13:0] res_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_ce0;
reg res_V_ce0;
reg res_V_we0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [8:0] ff_cast2_cast_fu_215_p1;
reg   [8:0] ff_cast2_cast_reg_474;
wire    ap_CS_fsm_state2;
wire   [4:0] ff_1_fu_225_p2;
reg   [4:0] ff_1_reg_482;
wire   [10:0] tmp_2_fu_277_p3;
reg   [10:0] tmp_2_reg_490;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_fu_231_p2;
wire   [3:0] ii_3_fu_291_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_3_fu_285_p2;
wire   [1:0] kk_1_fu_307_p2;
reg   [1:0] kk_1_reg_506;
wire    ap_CS_fsm_state5;
wire   [3:0] tmp_8_fu_313_p2;
reg   [3:0] tmp_8_reg_511;
wire   [0:0] tmp_4_fu_301_p2;
wire   [0:0] tmp_9_fu_322_p2;
reg   [0:0] tmp_9_reg_517;
wire    ap_CS_fsm_state6;
wire   [1:0] tmp_31_fu_327_p2;
reg   [1:0] tmp_31_reg_521;
wire   [11:0] tmp_10_fu_333_p2;
reg   [11:0] tmp_10_reg_526;
wire   [1:0] ll_1_fu_349_p2;
reg   [1:0] ll_1_reg_534;
wire    ap_CS_fsm_state7;
wire   [0:0] tmp_13_fu_361_p2;
reg   [0:0] tmp_13_reg_539;
wire   [0:0] tmp_11_fu_343_p2;
wire   [1:0] grp_fu_210_p2;
reg   [1:0] tmp_16_reg_543;
wire   [8:0] tmp1_fu_379_p2;
reg   [8:0] tmp1_reg_548;
wire   [11:0] tmp_19_fu_392_p2;
reg   [11:0] tmp_19_reg_553;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [12:0] data_V_load_reg_563;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_7_fu_430_p1;
reg   [63:0] tmp_7_reg_568;
wire    ap_CS_fsm_state12;
wire   [13:0] pool_V_q0;
wire    ap_CS_fsm_state13;
wire   [0:0] exitcond_i_i_fu_434_p2;
wire   [2:0] i_fu_445_p2;
reg   [2:0] i_reg_586;
wire   [3:0] jj_1_fu_451_p2;
reg   [13:0] pool_V_load_reg_596;
wire    ap_CS_fsm_state14;
wire   [13:0] y_V_3_fu_462_p3;
wire    ap_CS_fsm_state15;
reg   [1:0] pool_V_address0;
reg    pool_V_ce0;
reg    pool_V_we0;
reg   [13:0] pool_V_d0;
reg   [4:0] ff_reg_129;
reg   [3:0] ii_reg_141;
wire   [0:0] exitcond_fu_219_p2;
reg   [3:0] jj_reg_153;
reg   [1:0] kk_reg_165;
reg   [1:0] ll_reg_177;
wire    ap_CS_fsm_state11;
reg   [13:0] agg_result_V_i_i_reg_188;
reg   [2:0] i_i_i_reg_199;
wire   [63:0] tmp_15_fu_384_p1;
wire   [63:0] tmp_20_fu_397_p1;
wire   [63:0] tmp_17_fu_401_p1;
wire   [63:0] tmp_i_i_fu_440_p1;
wire   [13:0] extLd_fu_405_p1;
wire   [9:0] p_shl_fu_237_p3;
wire   [7:0] p_shl5_fu_249_p3;
wire   [10:0] p_shl_cast_fu_245_p1;
wire   [10:0] p_shl5_cast_fu_257_p1;
wire   [10:0] tmp_s_fu_261_p2;
wire   [5:0] tmp_1_fu_267_p4;
wire   [3:0] kk_cast8_fu_297_p1;
wire   [3:0] tmp_10_fu_333_p1;
wire   [3:0] ll_cast7_fu_339_p1;
wire   [3:0] tmp_12_fu_355_p2;
wire   [7:0] tmp_18_fu_367_p3;
wire   [8:0] tmp_66_cast_cast_fu_375_p1;
wire   [11:0] tmp1_cast_fu_389_p1;
wire   [6:0] tmp_5_fu_409_p3;
wire   [10:0] tmp_51_cast_fu_417_p1;
wire   [10:0] tmp_6_fu_421_p2;
wire  signed [31:0] tmp_53_cast_fu_426_p1;
wire   [0:0] tmp_i_i_35_fu_457_p2;
reg   [14:0] ap_NS_fsm;
wire   [11:0] tmp_10_fu_333_p10;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 15'd1;
end

pooling2d_cl_pool_V #(
    .DataWidth( 14 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
pool_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pool_V_address0),
    .ce0(pool_V_ce0),
    .we0(pool_V_we0),
    .d0(pool_V_d0),
    .q0(pool_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_V_i_i_reg_188 <= y_V_3_fu_462_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        agg_result_V_i_i_reg_188 <= pool_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ff_reg_129 <= ff_1_reg_482;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ff_reg_129 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_i_i_reg_199 <= i_reg_586;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        i_i_i_reg_199 <= 3'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ii_reg_141 <= 4'd0;
    end else if (((tmp_3_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ii_reg_141 <= ii_3_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        jj_reg_153 <= 4'd0;
    end else if (((exitcond_i_i_fu_434_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        jj_reg_153 <= jj_1_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_285_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kk_reg_165 <= 2'd0;
    end else if (((tmp_11_fu_343_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        kk_reg_165 <= kk_1_reg_506;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ll_reg_177 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ll_reg_177 <= ll_1_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_V_load_reg_563 <= data_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ff_1_reg_482 <= ff_1_fu_225_p2;
        ff_cast2_cast_reg_474[4 : 0] <= ff_cast2_cast_fu_215_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_i_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        i_reg_586 <= i_fu_445_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kk_1_reg_506 <= kk_1_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ll_1_reg_534 <= ll_1_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        pool_V_load_reg_596 <= pool_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_343_p2 == 1'd0) & (tmp_13_fu_361_p2 == 1'd0) & (tmp_9_reg_517 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp1_reg_548 <= tmp1_fu_379_p2;
        tmp_16_reg_543 <= grp_fu_210_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_10_reg_526 <= tmp_10_fu_333_p2;
        tmp_31_reg_521[1] <= tmp_31_fu_327_p2[1];
        tmp_9_reg_517 <= tmp_9_fu_322_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_343_p2 == 1'd0) & (tmp_9_reg_517 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_13_reg_539 <= tmp_13_fu_361_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_19_reg_553 <= tmp_19_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_2_reg_490 <= tmp_2_fu_277_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_7_reg_568[31 : 0] <= tmp_7_fu_430_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_4_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_8_reg_511 <= tmp_8_fu_313_p2;
    end
end

always @ (*) begin
    if (((exitcond_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_V_ce0 = 1'b1;
    end else begin
        data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        pool_V_address0 = tmp_i_i_fu_440_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        pool_V_address0 = tmp_17_fu_401_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        pool_V_address0 = tmp_15_fu_384_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        pool_V_address0 = 64'd0;
    end else begin
        pool_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state7))) begin
        pool_V_ce0 = 1'b1;
    end else begin
        pool_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        pool_V_d0 = extLd_fu_405_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        pool_V_d0 = 14'd8192;
    end else begin
        pool_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_13_reg_539 == 1'd0) & (tmp_9_reg_517 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state7) & (((tmp_11_fu_343_p2 == 1'd0) & (tmp_9_reg_517 == 1'd1)) | ((tmp_11_fu_343_p2 == 1'd0) & (tmp_13_fu_361_p2 == 1'd1)))))) begin
        pool_V_we0 = 1'b1;
    end else begin
        pool_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        res_V_ce0 = 1'b1;
    end else begin
        res_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_i_fu_434_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        res_V_we0 = 1'b1;
    end else begin
        res_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((tmp_3_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((tmp_4_fu_301_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((tmp_11_fu_343_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state7) & (((tmp_11_fu_343_p2 == 1'd0) & (tmp_9_reg_517 == 1'd1)) | ((tmp_11_fu_343_p2 == 1'd0) & (tmp_13_fu_361_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((exitcond_i_i_fu_434_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign data_V_address0 = tmp_20_fu_397_p1;

assign exitcond_fu_219_p2 = ((ff_reg_129 == 5'd16) ? 1'b1 : 1'b0);

assign exitcond_i_i_fu_434_p2 = ((i_i_i_reg_199 == 3'd4) ? 1'b1 : 1'b0);

assign extLd_fu_405_p1 = data_V_load_reg_563;

assign ff_1_fu_225_p2 = (ff_reg_129 + 5'd1);

assign ff_cast2_cast_fu_215_p1 = ff_reg_129;

assign grp_fu_210_p2 = (tmp_31_reg_521 + ll_reg_177);

assign i_fu_445_p2 = (i_i_i_reg_199 + 3'd1);

assign ii_3_fu_291_p2 = (ii_reg_141 + 4'd2);

assign jj_1_fu_451_p2 = (jj_reg_153 + 4'd2);

assign kk_1_fu_307_p2 = (kk_reg_165 + 2'd1);

assign kk_cast8_fu_297_p1 = kk_reg_165;

assign ll_1_fu_349_p2 = (ll_reg_177 + 2'd1);

assign ll_cast7_fu_339_p1 = ll_reg_177;

assign p_shl5_cast_fu_257_p1 = p_shl5_fu_249_p3;

assign p_shl5_fu_249_p3 = {{ii_reg_141}, {4'd0}};

assign p_shl_cast_fu_245_p1 = p_shl_fu_237_p3;

assign p_shl_fu_237_p3 = {{ii_reg_141}, {6'd0}};

assign res_V_address0 = tmp_7_reg_568;

assign res_V_d0 = agg_result_V_i_i_reg_188;

assign tmp1_cast_fu_389_p1 = tmp1_reg_548;

assign tmp1_fu_379_p2 = (ff_cast2_cast_reg_474 + tmp_66_cast_cast_fu_375_p1);

assign tmp_10_fu_333_p1 = tmp_10_fu_333_p10;

assign tmp_10_fu_333_p10 = tmp_8_reg_511;

assign tmp_10_fu_333_p2 = (12'd208 * tmp_10_fu_333_p1);

assign tmp_11_fu_343_p2 = ((ll_reg_177 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_12_fu_355_p2 = (jj_reg_153 + ll_cast7_fu_339_p1);

assign tmp_13_fu_361_p2 = ((tmp_12_fu_355_p2 > 4'd11) ? 1'b1 : 1'b0);

assign tmp_15_fu_384_p1 = grp_fu_210_p2;

assign tmp_17_fu_401_p1 = tmp_16_reg_543;

assign tmp_18_fu_367_p3 = {{tmp_12_fu_355_p2}, {4'd0}};

assign tmp_19_fu_392_p2 = (tmp_10_reg_526 + tmp1_cast_fu_389_p1);

assign tmp_1_fu_267_p4 = {{tmp_s_fu_261_p2[10:5]}};

assign tmp_20_fu_397_p1 = tmp_19_reg_553;

assign tmp_2_fu_277_p3 = {{tmp_1_fu_267_p4}, {ff_reg_129}};

assign tmp_31_fu_327_p2 = kk_reg_165 << 2'd1;

assign tmp_3_fu_285_p2 = ((jj_reg_153 < 4'd12) ? 1'b1 : 1'b0);

assign tmp_4_fu_301_p2 = ((kk_reg_165 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_51_cast_fu_417_p1 = tmp_5_fu_409_p3;

assign tmp_53_cast_fu_426_p1 = $signed(tmp_6_fu_421_p2);

assign tmp_5_fu_409_p3 = {{jj_reg_153}, {3'd0}};

assign tmp_66_cast_cast_fu_375_p1 = tmp_18_fu_367_p3;

assign tmp_6_fu_421_p2 = (tmp_51_cast_fu_417_p1 + tmp_2_reg_490);

assign tmp_7_fu_430_p1 = $unsigned(tmp_53_cast_fu_426_p1);

assign tmp_8_fu_313_p2 = (ii_reg_141 + kk_cast8_fu_297_p1);

assign tmp_9_fu_322_p2 = ((tmp_8_reg_511 > 4'd11) ? 1'b1 : 1'b0);

assign tmp_fu_231_p2 = ((ii_reg_141 < 4'd12) ? 1'b1 : 1'b0);

assign tmp_i_i_35_fu_457_p2 = (($signed(pool_V_load_reg_596) > $signed(agg_result_V_i_i_reg_188)) ? 1'b1 : 1'b0);

assign tmp_i_i_fu_440_p1 = i_i_i_reg_199;

assign tmp_s_fu_261_p2 = (p_shl_cast_fu_245_p1 - p_shl5_cast_fu_257_p1);

assign y_V_3_fu_462_p3 = ((tmp_i_i_35_fu_457_p2[0:0] === 1'b1) ? pool_V_load_reg_596 : agg_result_V_i_i_reg_188);

always @ (posedge ap_clk) begin
    ff_cast2_cast_reg_474[8:5] <= 4'b0000;
    tmp_31_reg_521[0] <= 1'b0;
    tmp_7_reg_568[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //pooling2d_cl_1
