// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv_2d_large_cl_1_HH_
#define _conv_2d_large_cl_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_large_rf_gt_ni_1.h"
#include "im2col_2d_cl_1.h"
#include "conv_2d_large_cl_1_data_col_V.h"
#include "dense_large_rf_gt_ni_1_acc_V.h"

namespace ap_rtl {

struct conv_2d_large_cl_1 : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > data_V_address0;
    sc_out< sc_logic > data_V_ce0;
    sc_in< sc_lv<14> > data_V_q0;
    sc_out< sc_lv<13> > res_V_address0;
    sc_out< sc_logic > res_V_ce0;
    sc_out< sc_logic > res_V_we0;
    sc_out< sc_lv<14> > res_V_d0;


    // Module declarations
    conv_2d_large_cl_1(sc_module_name name);
    SC_HAS_PROCESS(conv_2d_large_cl_1);

    ~conv_2d_large_cl_1();

    sc_trace_file* mVcdFile;

    conv_2d_large_cl_1_data_col_V* data_col_V_U;
    dense_large_rf_gt_ni_1_acc_V* res_V_assign_U;
    dense_large_rf_gt_ni_1* grp_dense_large_rf_gt_ni_1_fu_134;
    im2col_2d_cl_1* grp_im2col_2d_cl_1_fu_144;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<13> > next_mul_fu_155_p2;
    sc_signal< sc_lv<13> > next_mul_reg_237;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > i_7_fu_167_p2;
    sc_signal< sc_lv<5> > i_7_reg_245;
    sc_signal< sc_lv<5> > j_1_fu_179_p2;
    sc_signal< sc_lv<5> > j_1_reg_253;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<9> > tmp_135_cast_cast_fu_193_p1;
    sc_signal< sc_lv<9> > tmp_135_cast_cast_reg_258;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_ap_ready;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_ap_done;
    sc_signal< sc_lv<4> > k_1_fu_207_p2;
    sc_signal< sc_lv<4> > k_1_reg_266;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<13> > tmp_79_fu_222_p2;
    sc_signal< sc_lv<13> > tmp_79_reg_271;
    sc_signal< sc_lv<1> > tmp_78_fu_201_p2;
    sc_signal< sc_lv<14> > res_V_assign_q0;
    sc_signal< sc_lv<14> > res_V_assign_load_reg_281;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<4> > data_col_V_address0;
    sc_signal< sc_logic > data_col_V_ce0;
    sc_signal< sc_logic > data_col_V_we0;
    sc_signal< sc_lv<14> > data_col_V_q0;
    sc_signal< sc_lv<3> > res_V_assign_address0;
    sc_signal< sc_logic > res_V_assign_ce0;
    sc_signal< sc_logic > res_V_assign_we0;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_ap_start;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_ap_idle;
    sc_signal< sc_lv<4> > grp_dense_large_rf_gt_ni_1_fu_134_data_V_address0;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_data_V_ce0;
    sc_signal< sc_lv<3> > grp_dense_large_rf_gt_ni_1_fu_134_res_V_address0;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_res_V_ce0;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_res_V_we0;
    sc_signal< sc_lv<14> > grp_dense_large_rf_gt_ni_1_fu_134_res_V_d0;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_ap_start;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_ap_done;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_ap_idle;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_ap_ready;
    sc_signal< sc_lv<10> > grp_im2col_2d_cl_1_fu_144_data_V_address0;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_data_V_ce0;
    sc_signal< sc_lv<4> > grp_im2col_2d_cl_1_fu_144_data_col_V_address0;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_data_col_V_ce0;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_data_col_V_we0;
    sc_signal< sc_lv<14> > grp_im2col_2d_cl_1_fu_144_data_col_V_d0;
    sc_signal< sc_lv<5> > i_reg_87;
    sc_signal< sc_lv<1> > tmp_s_fu_173_p2;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<13> > phi_mul_reg_99;
    sc_signal< sc_lv<5> > j_reg_111;
    sc_signal< sc_lv<1> > tmp_fu_161_p2;
    sc_signal< sc_lv<4> > k_reg_123;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > grp_dense_large_rf_gt_ni_1_fu_134_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > grp_im2col_2d_cl_1_fu_144_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > tmp_81_fu_228_p1;
    sc_signal< sc_lv<64> > tmp_80_fu_233_p1;
    sc_signal< sc_lv<8> > tmp_77_fu_185_p3;
    sc_signal< sc_lv<9> > k_cast4_cast_fu_197_p1;
    sc_signal< sc_lv<9> > tmp1_fu_213_p2;
    sc_signal< sc_lv<13> > tmp1_cast_fu_218_p1;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_state4;
    static const sc_lv<9> ap_ST_fsm_state5;
    static const sc_lv<9> ap_ST_fsm_state6;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<13> ap_const_lv13_E8;
    static const sc_lv<5> ap_const_lv5_1D;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_data_V_address0();
    void thread_data_V_ce0();
    void thread_data_col_V_address0();
    void thread_data_col_V_ce0();
    void thread_data_col_V_we0();
    void thread_grp_dense_large_rf_gt_ni_1_fu_134_ap_start();
    void thread_grp_im2col_2d_cl_1_fu_144_ap_start();
    void thread_i_7_fu_167_p2();
    void thread_j_1_fu_179_p2();
    void thread_k_1_fu_207_p2();
    void thread_k_cast4_cast_fu_197_p1();
    void thread_next_mul_fu_155_p2();
    void thread_res_V_address0();
    void thread_res_V_assign_address0();
    void thread_res_V_assign_ce0();
    void thread_res_V_assign_we0();
    void thread_res_V_ce0();
    void thread_res_V_d0();
    void thread_res_V_we0();
    void thread_tmp1_cast_fu_218_p1();
    void thread_tmp1_fu_213_p2();
    void thread_tmp_135_cast_cast_fu_193_p1();
    void thread_tmp_77_fu_185_p3();
    void thread_tmp_78_fu_201_p2();
    void thread_tmp_79_fu_222_p2();
    void thread_tmp_80_fu_233_p1();
    void thread_tmp_81_fu_228_p1();
    void thread_tmp_fu_161_p2();
    void thread_tmp_s_fu_173_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
