// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_large_rf_gt_ni_3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_large_rf_gt_ni_3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_large_rf_gt_ni_3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state1 = "1";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state2 = "10";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state3 = "100";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state4 = "1000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state5 = "10000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state6 = "100000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state7 = "1000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state8 = "10000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state9 = "100000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state11 = "10000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state12 = "100000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<35> dense_large_rf_gt_ni_3::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1B = "11011";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_21 = "100001";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1 = "1";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_2 = "10";
const sc_lv<1> dense_large_rf_gt_ni_3::ap_const_lv1_0 = "0";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_3 = "11";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_4 = "100";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_5 = "101";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_15 = "10101";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_16 = "10110";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_17 = "10111";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_18 = "11000";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_19 = "11001";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1A = "11010";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1C = "11100";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1D = "11101";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1E = "11110";
const sc_lv<1> dense_large_rf_gt_ni_3::ap_const_lv1_1 = "1";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_1F = "11111";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_20 = "100000";
const sc_lv<7> dense_large_rf_gt_ni_3::ap_const_lv7_0 = "0000000";
const sc_lv<13> dense_large_rf_gt_ni_3::ap_const_lv13_0 = "0000000000000";
const sc_lv<2> dense_large_rf_gt_ni_3::ap_const_lv2_0 = "00";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_22 = "100010";
const sc_lv<14> dense_large_rf_gt_ni_3::ap_const_lv14_0 = "00000000000000";
const sc_lv<14> dense_large_rf_gt_ni_3::ap_const_lv14_2000 = "10000000000000";
const sc_lv<14> dense_large_rf_gt_ni_3::ap_const_lv14_1FFF = "1111111111111";
const sc_lv<7> dense_large_rf_gt_ni_3::ap_const_lv7_54 = "1010100";
const sc_lv<7> dense_large_rf_gt_ni_3::ap_const_lv7_1 = "1";
const sc_lv<13> dense_large_rf_gt_ni_3::ap_const_lv13_13B0 = "1001110110000";
const sc_lv<13> dense_large_rf_gt_ni_3::ap_const_lv13_1 = "1";
const sc_lv<2> dense_large_rf_gt_ni_3::ap_const_lv2_1 = "1";
const sc_lv<14> dense_large_rf_gt_ni_3::ap_const_lv14_13B0 = "1001110110000";
const sc_lv<4> dense_large_rf_gt_ni_3::ap_const_lv4_0 = "0000";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_E = "1110";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_D = "1101";
const sc_lv<15> dense_large_rf_gt_ni_3::ap_const_lv15_13B0 = "1001110110000";
const sc_lv<15> dense_large_rf_gt_ni_3::ap_const_lv15_275F = "10011101011111";
const sc_lv<7> dense_large_rf_gt_ni_3::ap_const_lv7_2A = "101010";
const sc_lv<32> dense_large_rf_gt_ni_3::ap_const_lv32_77 = "1110111";
const sc_lv<30> dense_large_rf_gt_ni_3::ap_const_lv30_6807 = "110100000000111";
const bool dense_large_rf_gt_ni_3::ap_const_boolean_1 = true;

dense_large_rf_gt_ni_3::dense_large_rf_gt_ni_3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    outidx4_U = new dense_large_rf_gt_ni_3_outidx4("outidx4_U");
    outidx4_U->clk(ap_clk);
    outidx4_U->reset(ap_rst);
    outidx4_U->address0(outidx4_address0);
    outidx4_U->ce0(outidx4_ce0);
    outidx4_U->q0(outidx4_q0);
    w14_V_U = new dense_large_rf_gt_ni_3_w14_V("w14_V_U");
    w14_V_U->clk(ap_clk);
    w14_V_U->reset(ap_rst);
    w14_V_U->address0(w14_V_address0);
    w14_V_U->ce0(w14_V_ce0);
    w14_V_U->q0(w14_V_q0);
    acc_V_U = new dense_large_rf_gt_ni_3_acc_V("acc_V_U");
    acc_V_U->clk(ap_clk);
    acc_V_U->reset(ap_rst);
    acc_V_U->address0(acc_V_address0);
    acc_V_U->ce0(acc_V_ce0);
    acc_V_U->we0(acc_V_we0);
    acc_V_U->d0(acc_V_d0);
    acc_V_U->q0(acc_V_q0);
    grp_product_fu_263 = new product("grp_product_fu_263");
    grp_product_fu_263->ap_clk(ap_clk);
    grp_product_fu_263->ap_rst(ap_rst);
    grp_product_fu_263->ap_start(grp_product_fu_263_ap_start);
    grp_product_fu_263->ap_done(grp_product_fu_263_ap_done);
    grp_product_fu_263->ap_idle(grp_product_fu_263_ap_idle);
    grp_product_fu_263->ap_ready(grp_product_fu_263_ap_ready);
    grp_product_fu_263->a_V(extLd_reg_583);
    grp_product_fu_263->w_V(tmp_52_reg_632);
    grp_product_fu_263->ap_return(grp_product_fu_263_ap_return);
    myproject_urem_14ns_14ns_14_18_seq_1_U55 = new myproject_urem_14ns_14ns_14_18_seq_1<1,18,14,14,14>("myproject_urem_14ns_14ns_14_18_seq_1_U55");
    myproject_urem_14ns_14ns_14_18_seq_1_U55->clk(ap_clk);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->reset(ap_rst);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->start(grp_fu_338_ap_start);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->done(grp_fu_338_ap_done);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->din0(w_index7_reg_242);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->din1(ap_var_for_const0);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->ce(ap_var_for_const1);
    myproject_urem_14ns_14ns_14_18_seq_1_U55->dout(grp_fu_338_p2);
    myproject_mul_mul_14ns_16ns_30_3_1_U56 = new myproject_mul_mul_14ns_16ns_30_3_1<1,3,14,16,30>("myproject_mul_mul_14ns_16ns_30_3_1_U56");
    myproject_mul_mul_14ns_16ns_30_3_1_U56->clk(ap_clk);
    myproject_mul_mul_14ns_16ns_30_3_1_U56->reset(ap_rst);
    myproject_mul_mul_14ns_16ns_30_3_1_U56->din0(grp_fu_535_p0);
    myproject_mul_mul_14ns_16ns_30_3_1_U56->din1(grp_fu_535_p1);
    myproject_mul_mul_14ns_16ns_30_3_1_U56->ce(ap_var_for_const1);
    myproject_mul_mul_14ns_16ns_30_3_1_U56->dout(grp_fu_535_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_45_reg_588 );
    sensitive << ( acc_V_addr_4_reg_637 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( overflow_reg_667 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( underflow_reg_671 );
    sensitive << ( brmerge9_reg_675 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( tmp_56_fu_530_p1 );
    sensitive << ( tmp_fu_286_p1 );
    sensitive << ( tmp_57_fu_409_p1 );

    SC_METHOD(thread_acc_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_45_reg_588 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( overflow_reg_667 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( underflow_reg_671 );
    sensitive << ( brmerge9_reg_675 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_acc_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_45_reg_588 );
    sensitive << ( p_Val2_16_reg_655 );
    sensitive << ( overflow_reg_667 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( underflow_reg_671 );
    sensitive << ( brmerge9_reg_675 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_acc_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_45_reg_588 );
    sensitive << ( overflow_reg_667 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( underflow_reg_671 );
    sensitive << ( brmerge9_reg_675 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( exitcond7_fu_274_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( tmp_55_fu_518_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( tmp_55_fu_518_p2 );

    SC_METHOD(thread_brmerge9_fu_468_p2);
    sensitive << ( p_Result_s_reg_648 );
    sensitive << ( p_Result_10_reg_660 );

    SC_METHOD(thread_data_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_54_fu_312_p1 );

    SC_METHOD(thread_data_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_exitcond7_fu_274_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iacc_reg_187 );

    SC_METHOD(thread_exitcond_fu_295_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( w_index_reg_198 );

    SC_METHOD(thread_extLd_fu_320_p1);
    sensitive << ( data_V_q0 );

    SC_METHOD(thread_grp_fu_338_ap_start);
    sensitive << ( tmp_45_fu_324_p3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_535_p0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( grp_fu_535_p00 );

    SC_METHOD(thread_grp_fu_535_p00);
    sensitive << ( w_index7_reg_242 );

    SC_METHOD(thread_grp_fu_535_p1);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_product_fu_263_ap_start);
    sensitive << ( grp_product_fu_263_ap_start_reg );

    SC_METHOD(thread_iacc_2_fu_280_p2);
    sensitive << ( iacc_reg_187 );

    SC_METHOD(thread_im_2_fu_332_p2);
    sensitive << ( im_reg_221 );

    SC_METHOD(thread_in_index_2_fu_500_p2);
    sensitive << ( in_index_reg_209 );

    SC_METHOD(thread_ir_fu_301_p2);
    sensitive << ( w_index_reg_198 );

    SC_METHOD(thread_ires_2_fu_524_p2);
    sensitive << ( ires_reg_252 );

    SC_METHOD(thread_lhs_V_fu_414_p1);
    sensitive << ( reg_269 );

    SC_METHOD(thread_out_index_4_fu_494_p2);
    sensitive << ( out_index7_reg_232 );

    SC_METHOD(thread_out_index_cast_fu_317_p1);
    sensitive << ( out_index_reg_568 );

    SC_METHOD(thread_outidx4_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_307_p1 );

    SC_METHOD(thread_outidx4_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_overflow_fu_453_p2);
    sensitive << ( p_Result_10_reg_660 );
    sensitive << ( tmp_21_fu_448_p2 );

    SC_METHOD(thread_p_Val2_16_fu_435_p2);
    sensitive << ( reg_269 );
    sensitive << ( p_Val2_14_reg_642 );

    SC_METHOD(thread_p_s_fu_511_p3);
    sensitive << ( in_index_2_reg_692 );
    sensitive << ( tmp_60_fu_506_p2 );

    SC_METHOD(thread_p_shl8_fu_368_p3);
    sensitive << ( tmp_6_fu_359_p4 );

    SC_METHOD(thread_res_V_address0);
    sensitive << ( tmp_56_reg_711 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_res_V_ce0);
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_res_V_d0);
    sensitive << ( reg_269 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_res_V_we0);
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_ret_V_fu_421_p2);
    sensitive << ( lhs_V_fu_414_p1 );
    sensitive << ( rhs_V_fu_418_p1 );

    SC_METHOD(thread_rhs_V_fu_418_p1);
    sensitive << ( p_Val2_14_reg_642 );

    SC_METHOD(thread_tmp_21_fu_448_p2);
    sensitive << ( p_Result_s_reg_648 );

    SC_METHOD(thread_tmp_32_fu_348_p1);
    sensitive << ( tmp_30_reg_602 );

    SC_METHOD(thread_tmp_45_fu_324_p3);
    sensitive << ( im_reg_221 );

    SC_METHOD(thread_tmp_47_fu_376_p3);
    sensitive << ( tmp_46_reg_617 );

    SC_METHOD(thread_tmp_48_fu_383_p1);
    sensitive << ( p_shl8_fu_368_p3 );

    SC_METHOD(thread_tmp_49_fu_387_p2);
    sensitive << ( tmp_47_fu_376_p3 );
    sensitive << ( tmp_48_fu_383_p1 );

    SC_METHOD(thread_tmp_50_fu_396_p1);
    sensitive << ( tmp_49_reg_627 );

    SC_METHOD(thread_tmp_51_fu_399_p2);
    sensitive << ( w14_V_load_cast_fu_393_p1 );
    sensitive << ( tmp_50_fu_396_p1 );

    SC_METHOD(thread_tmp_52_fu_405_p1);
    sensitive << ( tmp_51_fu_399_p2 );

    SC_METHOD(thread_tmp_54_fu_312_p1);
    sensitive << ( in_index_reg_209 );

    SC_METHOD(thread_tmp_55_fu_518_p2);
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ires_reg_252 );

    SC_METHOD(thread_tmp_56_fu_530_p1);
    sensitive << ( ires_reg_252 );

    SC_METHOD(thread_tmp_57_fu_409_p1);
    sensitive << ( out_index7_reg_232 );

    SC_METHOD(thread_tmp_58_fu_458_p2);
    sensitive << ( p_Result_10_reg_660 );

    SC_METHOD(thread_tmp_59_fu_488_p2);
    sensitive << ( tmp_45_reg_588 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( w_index_2_fu_476_p2 );

    SC_METHOD(thread_tmp_60_fu_506_p2);
    sensitive << ( in_index_2_reg_692 );
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_tmp_6_fu_359_p4);
    sensitive << ( mul_reg_607 );

    SC_METHOD(thread_tmp_fu_286_p1);
    sensitive << ( iacc_reg_187 );

    SC_METHOD(thread_tmp_s_fu_307_p1);
    sensitive << ( w_index_reg_198 );

    SC_METHOD(thread_underflow_fu_463_p2);
    sensitive << ( p_Result_s_reg_648 );
    sensitive << ( tmp_58_fu_458_p2 );

    SC_METHOD(thread_w14_V_address0);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_32_fu_348_p1 );

    SC_METHOD(thread_w14_V_ce0);
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_w14_V_load_cast_fu_393_p1);
    sensitive << ( w14_V_load_reg_622 );

    SC_METHOD(thread_w_index7_cast_fu_472_p1);
    sensitive << ( w_index7_reg_242 );

    SC_METHOD(thread_w_index_2_fu_476_p2);
    sensitive << ( w_index7_cast_fu_472_p1 );

    SC_METHOD(thread_w_index_4_cast_fu_482_p2);
    sensitive << ( w_index7_reg_242 );

    SC_METHOD(thread_w_index_cast_fu_291_p1);
    sensitive << ( w_index_reg_198 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( grp_product_fu_263_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_295_p2 );
    sensitive << ( tmp_45_fu_324_p3 );
    sensitive << ( tmp_45_reg_588 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( tmp_59_fu_488_p2 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( tmp_55_fu_518_p2 );
    sensitive << ( exitcond7_fu_274_p2 );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000001";
    grp_product_fu_263_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_large_rf_gt_ni_3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_address0, "(port)data_V_address0");
    sc_trace(mVcdFile, data_V_ce0, "(port)data_V_ce0");
    sc_trace(mVcdFile, data_V_q0, "(port)data_V_q0");
    sc_trace(mVcdFile, res_V_address0, "(port)res_V_address0");
    sc_trace(mVcdFile, res_V_ce0, "(port)res_V_ce0");
    sc_trace(mVcdFile, res_V_we0, "(port)res_V_we0");
    sc_trace(mVcdFile, res_V_d0, "(port)res_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, outidx4_address0, "outidx4_address0");
    sc_trace(mVcdFile, outidx4_ce0, "outidx4_ce0");
    sc_trace(mVcdFile, outidx4_q0, "outidx4_q0");
    sc_trace(mVcdFile, w14_V_address0, "w14_V_address0");
    sc_trace(mVcdFile, w14_V_ce0, "w14_V_ce0");
    sc_trace(mVcdFile, w14_V_q0, "w14_V_q0");
    sc_trace(mVcdFile, acc_V_q0, "acc_V_q0");
    sc_trace(mVcdFile, reg_269, "reg_269");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, grp_product_fu_263_ap_ready, "grp_product_fu_263_ap_ready");
    sc_trace(mVcdFile, grp_product_fu_263_ap_done, "grp_product_fu_263_ap_done");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, iacc_2_fu_280_p2, "iacc_2_fu_280_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, w_index_cast_fu_291_p1, "w_index_cast_fu_291_p1");
    sc_trace(mVcdFile, w_index_cast_reg_550, "w_index_cast_reg_550");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ir_fu_301_p2, "ir_fu_301_p2");
    sc_trace(mVcdFile, ir_reg_558, "ir_reg_558");
    sc_trace(mVcdFile, exitcond_fu_295_p2, "exitcond_fu_295_p2");
    sc_trace(mVcdFile, out_index_reg_568, "out_index_reg_568");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, out_index_cast_fu_317_p1, "out_index_cast_fu_317_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, extLd_fu_320_p1, "extLd_fu_320_p1");
    sc_trace(mVcdFile, extLd_reg_583, "extLd_reg_583");
    sc_trace(mVcdFile, tmp_45_fu_324_p3, "tmp_45_fu_324_p3");
    sc_trace(mVcdFile, tmp_45_reg_588, "tmp_45_reg_588");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, im_2_fu_332_p2, "im_2_fu_332_p2");
    sc_trace(mVcdFile, im_2_reg_592, "im_2_reg_592");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, grp_fu_338_p2, "grp_fu_338_p2");
    sc_trace(mVcdFile, tmp_30_reg_602, "tmp_30_reg_602");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, grp_fu_535_p2, "grp_fu_535_p2");
    sc_trace(mVcdFile, mul_reg_607, "mul_reg_607");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, tmp_46_reg_617, "tmp_46_reg_617");
    sc_trace(mVcdFile, w14_V_load_reg_622, "w14_V_load_reg_622");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, tmp_49_fu_387_p2, "tmp_49_fu_387_p2");
    sc_trace(mVcdFile, tmp_49_reg_627, "tmp_49_reg_627");
    sc_trace(mVcdFile, tmp_52_fu_405_p1, "tmp_52_fu_405_p1");
    sc_trace(mVcdFile, tmp_52_reg_632, "tmp_52_reg_632");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, acc_V_addr_4_reg_637, "acc_V_addr_4_reg_637");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, grp_product_fu_263_ap_return, "grp_product_fu_263_ap_return");
    sc_trace(mVcdFile, p_Val2_14_reg_642, "p_Val2_14_reg_642");
    sc_trace(mVcdFile, p_Result_s_reg_648, "p_Result_s_reg_648");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, p_Val2_16_fu_435_p2, "p_Val2_16_fu_435_p2");
    sc_trace(mVcdFile, p_Val2_16_reg_655, "p_Val2_16_reg_655");
    sc_trace(mVcdFile, p_Result_10_reg_660, "p_Result_10_reg_660");
    sc_trace(mVcdFile, overflow_fu_453_p2, "overflow_fu_453_p2");
    sc_trace(mVcdFile, overflow_reg_667, "overflow_reg_667");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, underflow_fu_463_p2, "underflow_fu_463_p2");
    sc_trace(mVcdFile, underflow_reg_671, "underflow_reg_671");
    sc_trace(mVcdFile, brmerge9_fu_468_p2, "brmerge9_fu_468_p2");
    sc_trace(mVcdFile, brmerge9_reg_675, "brmerge9_reg_675");
    sc_trace(mVcdFile, w_index_4_cast_fu_482_p2, "w_index_4_cast_fu_482_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, out_index_4_fu_494_p2, "out_index_4_fu_494_p2");
    sc_trace(mVcdFile, tmp_59_fu_488_p2, "tmp_59_fu_488_p2");
    sc_trace(mVcdFile, in_index_2_fu_500_p2, "in_index_2_fu_500_p2");
    sc_trace(mVcdFile, in_index_2_reg_692, "in_index_2_reg_692");
    sc_trace(mVcdFile, p_s_fu_511_p3, "p_s_fu_511_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, ires_2_fu_524_p2, "ires_2_fu_524_p2");
    sc_trace(mVcdFile, ires_2_reg_706, "ires_2_reg_706");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, tmp_56_fu_530_p1, "tmp_56_fu_530_p1");
    sc_trace(mVcdFile, tmp_56_reg_711, "tmp_56_reg_711");
    sc_trace(mVcdFile, tmp_55_fu_518_p2, "tmp_55_fu_518_p2");
    sc_trace(mVcdFile, acc_V_address0, "acc_V_address0");
    sc_trace(mVcdFile, acc_V_ce0, "acc_V_ce0");
    sc_trace(mVcdFile, acc_V_we0, "acc_V_we0");
    sc_trace(mVcdFile, acc_V_d0, "acc_V_d0");
    sc_trace(mVcdFile, grp_product_fu_263_ap_start, "grp_product_fu_263_ap_start");
    sc_trace(mVcdFile, grp_product_fu_263_ap_idle, "grp_product_fu_263_ap_idle");
    sc_trace(mVcdFile, iacc_reg_187, "iacc_reg_187");
    sc_trace(mVcdFile, exitcond7_fu_274_p2, "exitcond7_fu_274_p2");
    sc_trace(mVcdFile, w_index_reg_198, "w_index_reg_198");
    sc_trace(mVcdFile, in_index_reg_209, "in_index_reg_209");
    sc_trace(mVcdFile, im_reg_221, "im_reg_221");
    sc_trace(mVcdFile, out_index7_reg_232, "out_index7_reg_232");
    sc_trace(mVcdFile, w_index7_reg_242, "w_index7_reg_242");
    sc_trace(mVcdFile, ires_reg_252, "ires_reg_252");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, grp_product_fu_263_ap_start_reg, "grp_product_fu_263_ap_start_reg");
    sc_trace(mVcdFile, tmp_fu_286_p1, "tmp_fu_286_p1");
    sc_trace(mVcdFile, tmp_s_fu_307_p1, "tmp_s_fu_307_p1");
    sc_trace(mVcdFile, tmp_54_fu_312_p1, "tmp_54_fu_312_p1");
    sc_trace(mVcdFile, tmp_32_fu_348_p1, "tmp_32_fu_348_p1");
    sc_trace(mVcdFile, tmp_57_fu_409_p1, "tmp_57_fu_409_p1");
    sc_trace(mVcdFile, tmp_6_fu_359_p4, "tmp_6_fu_359_p4");
    sc_trace(mVcdFile, p_shl8_fu_368_p3, "p_shl8_fu_368_p3");
    sc_trace(mVcdFile, tmp_47_fu_376_p3, "tmp_47_fu_376_p3");
    sc_trace(mVcdFile, tmp_48_fu_383_p1, "tmp_48_fu_383_p1");
    sc_trace(mVcdFile, w14_V_load_cast_fu_393_p1, "w14_V_load_cast_fu_393_p1");
    sc_trace(mVcdFile, tmp_50_fu_396_p1, "tmp_50_fu_396_p1");
    sc_trace(mVcdFile, tmp_51_fu_399_p2, "tmp_51_fu_399_p2");
    sc_trace(mVcdFile, lhs_V_fu_414_p1, "lhs_V_fu_414_p1");
    sc_trace(mVcdFile, rhs_V_fu_418_p1, "rhs_V_fu_418_p1");
    sc_trace(mVcdFile, ret_V_fu_421_p2, "ret_V_fu_421_p2");
    sc_trace(mVcdFile, tmp_21_fu_448_p2, "tmp_21_fu_448_p2");
    sc_trace(mVcdFile, tmp_58_fu_458_p2, "tmp_58_fu_458_p2");
    sc_trace(mVcdFile, w_index7_cast_fu_472_p1, "w_index7_cast_fu_472_p1");
    sc_trace(mVcdFile, w_index_2_fu_476_p2, "w_index_2_fu_476_p2");
    sc_trace(mVcdFile, tmp_60_fu_506_p2, "tmp_60_fu_506_p2");
    sc_trace(mVcdFile, grp_fu_535_p0, "grp_fu_535_p0");
    sc_trace(mVcdFile, grp_fu_535_p1, "grp_fu_535_p1");
    sc_trace(mVcdFile, grp_fu_338_ap_start, "grp_fu_338_ap_start");
    sc_trace(mVcdFile, grp_fu_338_ap_done, "grp_fu_338_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_535_p00, "grp_fu_535_p00");
#endif

    }
}

dense_large_rf_gt_ni_3::~dense_large_rf_gt_ni_3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete outidx4_U;
    delete w14_V_U;
    delete acc_V_U;
    delete grp_product_fu_263;
    delete myproject_urem_14ns_14ns_14_18_seq_1_U55;
    delete myproject_mul_mul_14ns_16ns_30_3_1_U56;
}

void dense_large_rf_gt_ni_3::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void dense_large_rf_gt_ni_3::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv14_13B0;
}

void dense_large_rf_gt_ni_3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_product_fu_263_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
            grp_product_fu_263_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_product_fu_263_ap_ready.read())) {
            grp_product_fu_263_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        iacc_reg_187 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_274_p2.read()))) {
        iacc_reg_187 = iacc_2_fu_280_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_fu_488_p2.read()))) {
        im_reg_221 = im_2_reg_592.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        im_reg_221 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond7_fu_274_p2.read()))) {
        in_index_reg_209 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        in_index_reg_209 = p_s_fu_511_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_295_p2.read(), ap_const_lv1_1))) {
        ires_reg_252 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        ires_reg_252 = ires_2_reg_706.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_fu_488_p2.read()))) {
        out_index7_reg_232 = out_index_4_fu_494_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        out_index7_reg_232 = out_index_cast_fu_317_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_fu_488_p2.read()))) {
        w_index7_reg_242 = w_index_4_cast_fu_482_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        w_index7_reg_242 = w_index_cast_reg_550.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond7_fu_274_p2.read()))) {
        w_index_reg_198 = ap_const_lv13_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        w_index_reg_198 = ir_reg_558.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        acc_V_addr_4_reg_637 =  (sc_lv<7>) (tmp_57_fu_409_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
        brmerge9_reg_675 = brmerge9_fu_468_p2.read();
        overflow_reg_667 = overflow_fu_453_p2.read();
        underflow_reg_671 = underflow_fu_463_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        extLd_reg_583 = extLd_fu_320_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        im_2_reg_592 = im_2_fu_332_p2.read();
        tmp_45_reg_588 = im_reg_221.read().range(1, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && (esl_seteq<1,1,1>(tmp_59_fu_488_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_45_reg_588.read(), ap_const_lv1_1)))) {
        in_index_2_reg_692 = in_index_2_fu_500_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ir_reg_558 = ir_fu_301_p2.read();
        w_index_cast_reg_550 = w_index_cast_fu_291_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        ires_2_reg_706 = ires_2_fu_524_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        mul_reg_607 = grp_fu_535_p2.read();
        tmp_46_reg_617 = grp_fu_535_p2.read().range(27, 27);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_index_reg_568 = outidx4_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        p_Result_10_reg_660 = p_Val2_16_fu_435_p2.read().range(13, 13);
        p_Result_s_reg_648 = ret_V_fu_421_p2.read().range(14, 14);
        p_Val2_16_reg_655 = p_Val2_16_fu_435_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && esl_seteq<1,1,1>(grp_product_fu_263_ap_done.read(), ap_const_logic_1))) {
        p_Val2_14_reg_642 = grp_product_fu_263_ap_return.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && 
  esl_seteq<1,1,1>(grp_product_fu_263_ap_done.read(), ap_const_logic_1)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()))) {
        reg_269 = acc_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        tmp_30_reg_602 = grp_fu_338_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        tmp_49_reg_627 = tmp_49_fu_387_p2.read();
        w14_V_load_reg_622 = w14_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        tmp_52_reg_632 = tmp_52_fu_405_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_55_fu_518_p2.read()))) {
        tmp_56_reg_711 = tmp_56_fu_530_p1.read();
    }
}

void dense_large_rf_gt_ni_3::thread_acc_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        acc_V_address0 =  (sc_lv<7>) (tmp_56_fu_530_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
                 esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, overflow_reg_667.read()) && 
                 esl_seteq<1,1,1>(underflow_reg_671.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
                 esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(overflow_reg_667.read(), ap_const_lv1_1)))) {
        acc_V_address0 = acc_V_addr_4_reg_637.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        acc_V_address0 =  (sc_lv<7>) (tmp_57_fu_409_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        acc_V_address0 =  (sc_lv<7>) (tmp_fu_286_p1.read());
    } else {
        acc_V_address0 = "XXXXXXX";
    }
}

void dense_large_rf_gt_ni_3::thread_acc_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
          esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, overflow_reg_667.read()) && 
          esl_seteq<1,1,1>(underflow_reg_671.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
          esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(overflow_reg_667.read(), ap_const_lv1_1)))) {
        acc_V_ce0 = ap_const_logic_1;
    } else {
        acc_V_ce0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_acc_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
         esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(overflow_reg_667.read(), ap_const_lv1_1))) {
        acc_V_d0 = ap_const_lv14_1FFF;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
                esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, overflow_reg_667.read()) && 
                esl_seteq<1,1,1>(underflow_reg_671.read(), ap_const_lv1_1))) {
        acc_V_d0 = ap_const_lv14_2000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
        acc_V_d0 = p_Val2_16_reg_655.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        acc_V_d0 = ap_const_lv14_0;
    } else {
        acc_V_d0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void dense_large_rf_gt_ni_3::thread_acc_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_274_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
          esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, overflow_reg_667.read()) && 
          esl_seteq<1,1,1>(underflow_reg_671.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && 
          esl_seteq<1,1,1>(brmerge9_reg_675.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(overflow_reg_667.read(), ap_const_lv1_1)))) {
        acc_V_we0 = ap_const_logic_1;
    } else {
        acc_V_we0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void dense_large_rf_gt_ni_3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dense_large_rf_gt_ni_3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_55_fu_518_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_55_fu_518_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_brmerge9_fu_468_p2() {
    brmerge9_fu_468_p2 = (p_Result_s_reg_648.read() ^ p_Result_10_reg_660.read());
}

void dense_large_rf_gt_ni_3::thread_data_V_address0() {
    data_V_address0 =  (sc_lv<7>) (tmp_54_fu_312_p1.read());
}

void dense_large_rf_gt_ni_3::thread_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_V_ce0 = ap_const_logic_1;
    } else {
        data_V_ce0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_exitcond7_fu_274_p2() {
    exitcond7_fu_274_p2 = (!iacc_reg_187.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(iacc_reg_187.read() == ap_const_lv7_54);
}

void dense_large_rf_gt_ni_3::thread_exitcond_fu_295_p2() {
    exitcond_fu_295_p2 = (!w_index_reg_198.read().is_01() || !ap_const_lv13_13B0.is_01())? sc_lv<1>(): sc_lv<1>(w_index_reg_198.read() == ap_const_lv13_13B0);
}

void dense_large_rf_gt_ni_3::thread_extLd_fu_320_p1() {
    extLd_fu_320_p1 = esl_zext<14,13>(data_V_q0.read());
}

void dense_large_rf_gt_ni_3::thread_grp_fu_338_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_fu_324_p3.read()))) {
        grp_fu_338_ap_start = ap_const_logic_1;
    } else {
        grp_fu_338_ap_start = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_grp_fu_535_p0() {
    grp_fu_535_p0 =  (sc_lv<14>) (grp_fu_535_p00.read());
}

void dense_large_rf_gt_ni_3::thread_grp_fu_535_p00() {
    grp_fu_535_p00 = esl_zext<30,14>(w_index7_reg_242.read());
}

void dense_large_rf_gt_ni_3::thread_grp_fu_535_p1() {
    grp_fu_535_p1 =  (sc_lv<16>) (ap_const_lv30_6807);
}

void dense_large_rf_gt_ni_3::thread_grp_product_fu_263_ap_start() {
    grp_product_fu_263_ap_start = grp_product_fu_263_ap_start_reg.read();
}

void dense_large_rf_gt_ni_3::thread_iacc_2_fu_280_p2() {
    iacc_2_fu_280_p2 = (!iacc_reg_187.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(iacc_reg_187.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dense_large_rf_gt_ni_3::thread_im_2_fu_332_p2() {
    im_2_fu_332_p2 = (!im_reg_221.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(im_reg_221.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dense_large_rf_gt_ni_3::thread_in_index_2_fu_500_p2() {
    in_index_2_fu_500_p2 = (!in_index_reg_209.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(in_index_reg_209.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void dense_large_rf_gt_ni_3::thread_ir_fu_301_p2() {
    ir_fu_301_p2 = (!w_index_reg_198.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(w_index_reg_198.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void dense_large_rf_gt_ni_3::thread_ires_2_fu_524_p2() {
    ires_2_fu_524_p2 = (!ires_reg_252.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(ires_reg_252.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dense_large_rf_gt_ni_3::thread_lhs_V_fu_414_p1() {
    lhs_V_fu_414_p1 = esl_sext<15,14>(reg_269.read());
}

void dense_large_rf_gt_ni_3::thread_out_index_4_fu_494_p2() {
    out_index_4_fu_494_p2 = (!out_index7_reg_232.read().is_01() || !ap_const_lv7_2A.is_01())? sc_lv<7>(): (sc_biguint<7>(out_index7_reg_232.read()) + sc_biguint<7>(ap_const_lv7_2A));
}

void dense_large_rf_gt_ni_3::thread_out_index_cast_fu_317_p1() {
    out_index_cast_fu_317_p1 = esl_zext<7,6>(out_index_reg_568.read());
}

void dense_large_rf_gt_ni_3::thread_outidx4_address0() {
    outidx4_address0 =  (sc_lv<13>) (tmp_s_fu_307_p1.read());
}

void dense_large_rf_gt_ni_3::thread_outidx4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        outidx4_ce0 = ap_const_logic_1;
    } else {
        outidx4_ce0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_overflow_fu_453_p2() {
    overflow_fu_453_p2 = (p_Result_10_reg_660.read() & tmp_21_fu_448_p2.read());
}

void dense_large_rf_gt_ni_3::thread_p_Val2_16_fu_435_p2() {
    p_Val2_16_fu_435_p2 = (!reg_269.read().is_01() || !p_Val2_14_reg_642.read().is_01())? sc_lv<14>(): (sc_bigint<14>(reg_269.read()) + sc_bigint<14>(p_Val2_14_reg_642.read()));
}

void dense_large_rf_gt_ni_3::thread_p_s_fu_511_p3() {
    p_s_fu_511_p3 = (!tmp_60_fu_506_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_60_fu_506_p2.read()[0].to_bool())? ap_const_lv32_0: in_index_2_reg_692.read());
}

void dense_large_rf_gt_ni_3::thread_p_shl8_fu_368_p3() {
    p_shl8_fu_368_p3 = esl_concat<2,1>(tmp_6_fu_359_p4.read(), ap_const_lv1_0);
}

void dense_large_rf_gt_ni_3::thread_res_V_address0() {
    res_V_address0 =  (sc_lv<7>) (tmp_56_reg_711.read());
}

void dense_large_rf_gt_ni_3::thread_res_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        res_V_ce0 = ap_const_logic_1;
    } else {
        res_V_ce0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_res_V_d0() {
    res_V_d0 = reg_269.read();
}

void dense_large_rf_gt_ni_3::thread_res_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        res_V_we0 = ap_const_logic_1;
    } else {
        res_V_we0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_ret_V_fu_421_p2() {
    ret_V_fu_421_p2 = (!lhs_V_fu_414_p1.read().is_01() || !rhs_V_fu_418_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(lhs_V_fu_414_p1.read()) + sc_bigint<15>(rhs_V_fu_418_p1.read()));
}

void dense_large_rf_gt_ni_3::thread_rhs_V_fu_418_p1() {
    rhs_V_fu_418_p1 = esl_sext<15,14>(p_Val2_14_reg_642.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_21_fu_448_p2() {
    tmp_21_fu_448_p2 = (p_Result_s_reg_648.read() ^ ap_const_lv1_1);
}

void dense_large_rf_gt_ni_3::thread_tmp_32_fu_348_p1() {
    tmp_32_fu_348_p1 = esl_zext<64,14>(tmp_30_reg_602.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_45_fu_324_p3() {
    tmp_45_fu_324_p3 = im_reg_221.read().range(1, 1);
}

void dense_large_rf_gt_ni_3::thread_tmp_47_fu_376_p3() {
    tmp_47_fu_376_p3 = esl_concat<1,4>(tmp_46_reg_617.read(), ap_const_lv4_0);
}

void dense_large_rf_gt_ni_3::thread_tmp_48_fu_383_p1() {
    tmp_48_fu_383_p1 = esl_zext<5,3>(p_shl8_fu_368_p3.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_49_fu_387_p2() {
    tmp_49_fu_387_p2 = (!tmp_47_fu_376_p3.read().is_01() || !tmp_48_fu_383_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_47_fu_376_p3.read()) - sc_biguint<5>(tmp_48_fu_383_p1.read()));
}

void dense_large_rf_gt_ni_3::thread_tmp_50_fu_396_p1() {
    tmp_50_fu_396_p1 = esl_zext<28,5>(tmp_49_reg_627.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_51_fu_399_p2() {
    tmp_51_fu_399_p2 = (!tmp_50_fu_396_p1.read().is_01())? sc_lv<28>(): w14_V_load_cast_fu_393_p1.read() >> (unsigned short)tmp_50_fu_396_p1.read().to_uint();
}

void dense_large_rf_gt_ni_3::thread_tmp_52_fu_405_p1() {
    tmp_52_fu_405_p1 = tmp_51_fu_399_p2.read().range(14-1, 0);
}

void dense_large_rf_gt_ni_3::thread_tmp_54_fu_312_p1() {
    tmp_54_fu_312_p1 = esl_sext<64,32>(in_index_reg_209.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_55_fu_518_p2() {
    tmp_55_fu_518_p2 = (!ires_reg_252.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(ires_reg_252.read() == ap_const_lv7_54);
}

void dense_large_rf_gt_ni_3::thread_tmp_56_fu_530_p1() {
    tmp_56_fu_530_p1 = esl_zext<64,7>(ires_reg_252.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_57_fu_409_p1() {
    tmp_57_fu_409_p1 = esl_zext<64,7>(out_index7_reg_232.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_58_fu_458_p2() {
    tmp_58_fu_458_p2 = (p_Result_10_reg_660.read() ^ ap_const_lv1_1);
}

void dense_large_rf_gt_ni_3::thread_tmp_59_fu_488_p2() {
    tmp_59_fu_488_p2 = (!w_index_2_fu_476_p2.read().is_01() || !ap_const_lv15_275F.is_01())? sc_lv<1>(): (sc_biguint<15>(w_index_2_fu_476_p2.read()) > sc_biguint<15>(ap_const_lv15_275F));
}

void dense_large_rf_gt_ni_3::thread_tmp_60_fu_506_p2() {
    tmp_60_fu_506_p2 = (!in_index_2_reg_692.read().is_01() || !ap_const_lv32_77.is_01())? sc_lv<1>(): (sc_bigint<32>(in_index_2_reg_692.read()) > sc_bigint<32>(ap_const_lv32_77));
}

void dense_large_rf_gt_ni_3::thread_tmp_6_fu_359_p4() {
    tmp_6_fu_359_p4 = mul_reg_607.read().range(28, 27);
}

void dense_large_rf_gt_ni_3::thread_tmp_fu_286_p1() {
    tmp_fu_286_p1 = esl_zext<64,7>(iacc_reg_187.read());
}

void dense_large_rf_gt_ni_3::thread_tmp_s_fu_307_p1() {
    tmp_s_fu_307_p1 = esl_zext<64,13>(w_index_reg_198.read());
}

void dense_large_rf_gt_ni_3::thread_underflow_fu_463_p2() {
    underflow_fu_463_p2 = (p_Result_s_reg_648.read() & tmp_58_fu_458_p2.read());
}

void dense_large_rf_gt_ni_3::thread_w14_V_address0() {
    w14_V_address0 =  (sc_lv<13>) (tmp_32_fu_348_p1.read());
}

void dense_large_rf_gt_ni_3::thread_w14_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        w14_V_ce0 = ap_const_logic_1;
    } else {
        w14_V_ce0 = ap_const_logic_0;
    }
}

void dense_large_rf_gt_ni_3::thread_w14_V_load_cast_fu_393_p1() {
    w14_V_load_cast_fu_393_p1 = esl_sext<28,25>(w14_V_load_reg_622.read());
}

void dense_large_rf_gt_ni_3::thread_w_index7_cast_fu_472_p1() {
    w_index7_cast_fu_472_p1 = esl_zext<15,14>(w_index7_reg_242.read());
}

void dense_large_rf_gt_ni_3::thread_w_index_2_fu_476_p2() {
    w_index_2_fu_476_p2 = (!w_index7_cast_fu_472_p1.read().is_01() || !ap_const_lv15_13B0.is_01())? sc_lv<15>(): (sc_biguint<15>(w_index7_cast_fu_472_p1.read()) + sc_biguint<15>(ap_const_lv15_13B0));
}

void dense_large_rf_gt_ni_3::thread_w_index_4_cast_fu_482_p2() {
    w_index_4_cast_fu_482_p2 = (!w_index7_reg_242.read().is_01() || !ap_const_lv14_13B0.is_01())? sc_lv<14>(): (sc_biguint<14>(w_index7_reg_242.read()) + sc_biguint<14>(ap_const_lv14_13B0));
}

void dense_large_rf_gt_ni_3::thread_w_index_cast_fu_291_p1() {
    w_index_cast_fu_291_p1 = esl_zext<14,13>(w_index_reg_198.read());
}

void dense_large_rf_gt_ni_3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond7_fu_274_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_295_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state33;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(tmp_45_fu_324_p3.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state31;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && esl_seteq<1,1,1>(grp_product_fu_263_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state29;
            } else {
                ap_NS_fsm = ap_ST_fsm_state28;
            }
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_reg_588.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_fu_488_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state32;
            }
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4294967296 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_55_fu_518_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state34;
            }
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<35>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

