// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_large_rf_gt_ni_2_HH_
#define _dense_large_rf_gt_ni_2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "product.h"
#include "myproject_urem_11ns_10ns_11_15_seq_1.h"
#include "myproject_mul_mul_11ns_13ns_24_3_1.h"
#include "dense_large_rf_gt_ni_2_outidx.h"
#include "dense_large_rf_gt_ni_2_w17_V.h"
#include "dense_large_rf_gt_ni_2_acc_V.h"

namespace ap_rtl {

struct dense_large_rf_gt_ni_2 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<7> > data_V_address0;
    sc_out< sc_logic > data_V_ce0;
    sc_in< sc_lv<13> > data_V_q0;
    sc_out< sc_lv<4> > res_V_address0;
    sc_out< sc_logic > res_V_ce0;
    sc_out< sc_logic > res_V_we0;
    sc_out< sc_lv<14> > res_V_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    dense_large_rf_gt_ni_2(sc_module_name name);
    SC_HAS_PROCESS(dense_large_rf_gt_ni_2);

    ~dense_large_rf_gt_ni_2();

    sc_trace_file* mVcdFile;

    dense_large_rf_gt_ni_2_outidx* outidx_U;
    dense_large_rf_gt_ni_2_w17_V* w17_V_U;
    dense_large_rf_gt_ni_2_acc_V* acc_V_U;
    product* grp_product_fu_259;
    myproject_urem_11ns_10ns_11_15_seq_1<1,15,11,10,11>* myproject_urem_11ns_10ns_11_15_seq_1_U68;
    myproject_mul_mul_11ns_13ns_24_3_1<1,3,11,13,24>* myproject_mul_mul_11ns_13ns_24_3_1_U69;
    sc_signal< sc_lv<31> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<9> > outidx_address0;
    sc_signal< sc_logic > outidx_ce0;
    sc_signal< sc_lv<3> > outidx_q0;
    sc_signal< sc_lv<9> > w17_V_address0;
    sc_signal< sc_logic > w17_V_ce0;
    sc_signal< sc_lv<25> > w17_V_q0;
    sc_signal< sc_lv<14> > acc_V_q0;
    sc_signal< sc_lv<14> > reg_265;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_logic > grp_product_fu_259_ap_ready;
    sc_signal< sc_logic > grp_product_fu_259_ap_done;
    sc_signal< sc_logic > ap_CS_fsm_state30;
    sc_signal< sc_lv<4> > iacc_3_fu_276_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<11> > w_index_cast_fu_287_p1;
    sc_signal< sc_lv<11> > w_index_cast_reg_543;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<9> > ir_fu_297_p2;
    sc_signal< sc_lv<9> > ir_reg_551;
    sc_signal< sc_lv<1> > exitcond_fu_291_p2;
    sc_signal< sc_lv<3> > out_index_reg_561;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > out_index_cast_fu_313_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<14> > extLd_fu_316_p1;
    sc_signal< sc_lv<14> > extLd_reg_576;
    sc_signal< sc_lv<1> > tmp_59_fu_320_p3;
    sc_signal< sc_lv<1> > tmp_59_reg_581;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<2> > im_3_fu_328_p2;
    sc_signal< sc_lv<2> > im_3_reg_585;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<11> > grp_fu_334_p2;
    sc_signal< sc_lv<11> > tmp_21_reg_595;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_lv<24> > grp_fu_528_p2;
    sc_signal< sc_lv<24> > mul_reg_600;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<1> > tmp_60_reg_610;
    sc_signal< sc_lv<25> > w17_V_load_reg_615;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<5> > tmp_67_fu_383_p2;
    sc_signal< sc_lv<5> > tmp_67_reg_620;
    sc_signal< sc_lv<14> > tmp_73_fu_401_p1;
    sc_signal< sc_lv<14> > tmp_73_reg_625;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<4> > acc_V_addr_6_reg_630;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<14> > grp_product_fu_259_ap_return;
    sc_signal< sc_lv<14> > p_Val2_17_reg_635;
    sc_signal< sc_lv<1> > overflow_fu_451_p2;
    sc_signal< sc_lv<1> > overflow_reg_641;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<1> > underflow_fu_463_p2;
    sc_signal< sc_lv<1> > underflow_reg_645;
    sc_signal< sc_lv<1> > brmerge8_fu_469_p2;
    sc_signal< sc_lv<1> > brmerge8_reg_649;
    sc_signal< sc_lv<11> > w_index_3_fu_475_p2;
    sc_signal< sc_logic > ap_CS_fsm_state27;
    sc_signal< sc_lv<4> > out_index_3_fu_487_p2;
    sc_signal< sc_lv<1> > tmp_70_fu_481_p2;
    sc_signal< sc_lv<32> > in_index_3_fu_493_p2;
    sc_signal< sc_lv<32> > in_index_3_reg_666;
    sc_signal< sc_lv<32> > p_s_fu_504_p3;
    sc_signal< sc_logic > ap_CS_fsm_state28;
    sc_signal< sc_lv<4> > ires_3_fu_517_p2;
    sc_signal< sc_lv<4> > ires_3_reg_680;
    sc_signal< sc_logic > ap_CS_fsm_state29;
    sc_signal< sc_lv<64> > tmp_63_fu_523_p1;
    sc_signal< sc_lv<64> > tmp_63_reg_685;
    sc_signal< sc_lv<1> > tmp_62_fu_511_p2;
    sc_signal< sc_lv<4> > acc_V_address0;
    sc_signal< sc_logic > acc_V_ce0;
    sc_signal< sc_logic > acc_V_we0;
    sc_signal< sc_lv<14> > acc_V_d0;
    sc_signal< sc_logic > grp_product_fu_259_ap_start;
    sc_signal< sc_logic > grp_product_fu_259_ap_idle;
    sc_signal< sc_lv<4> > iacc_reg_183;
    sc_signal< sc_lv<1> > exitcond6_fu_270_p2;
    sc_signal< sc_lv<9> > w_index_reg_194;
    sc_signal< sc_lv<32> > in_index_reg_205;
    sc_signal< sc_lv<2> > im_reg_217;
    sc_signal< sc_lv<4> > out_index5_reg_228;
    sc_signal< sc_lv<11> > w_index5_reg_238;
    sc_signal< sc_lv<4> > ires_reg_248;
    sc_signal< sc_logic > ap_CS_fsm_state31;
    sc_signal< sc_logic > grp_product_fu_259_ap_start_reg;
    sc_signal< sc_lv<64> > tmp_fu_282_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_303_p1;
    sc_signal< sc_lv<64> > tmp_61_fu_308_p1;
    sc_signal< sc_lv<64> > tmp_23_fu_344_p1;
    sc_signal< sc_lv<64> > tmp_64_fu_405_p1;
    sc_signal< sc_lv<14> > p_Val2_19_fu_431_p2;
    sc_signal< sc_lv<10> > grp_fu_334_p1;
    sc_signal< sc_lv<2> > tmp_8_fu_355_p4;
    sc_signal< sc_lv<3> > p_shl8_fu_364_p3;
    sc_signal< sc_lv<5> > tmp_65_fu_372_p3;
    sc_signal< sc_lv<5> > tmp_66_fu_379_p1;
    sc_signal< sc_lv<28> > w17_V_load_cast_fu_389_p1;
    sc_signal< sc_lv<28> > tmp_68_fu_392_p1;
    sc_signal< sc_lv<28> > tmp_72_fu_395_p2;
    sc_signal< sc_lv<15> > lhs_V_fu_410_p1;
    sc_signal< sc_lv<15> > rhs_V_fu_414_p1;
    sc_signal< sc_lv<15> > ret_V_fu_417_p2;
    sc_signal< sc_lv<1> > p_Result_s_fu_423_p3;
    sc_signal< sc_lv<1> > p_Result_11_fu_437_p3;
    sc_signal< sc_lv<1> > tmp_20_fu_445_p2;
    sc_signal< sc_lv<1> > tmp_69_fu_457_p2;
    sc_signal< sc_lv<1> > tmp_71_fu_499_p2;
    sc_signal< sc_lv<11> > grp_fu_528_p0;
    sc_signal< sc_lv<13> > grp_fu_528_p1;
    sc_signal< sc_logic > grp_fu_334_ap_start;
    sc_signal< sc_logic > grp_fu_334_ap_done;
    sc_signal< sc_lv<31> > ap_NS_fsm;
    sc_signal< sc_lv<24> > grp_fu_528_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<31> ap_ST_fsm_state1;
    static const sc_lv<31> ap_ST_fsm_state2;
    static const sc_lv<31> ap_ST_fsm_state3;
    static const sc_lv<31> ap_ST_fsm_state4;
    static const sc_lv<31> ap_ST_fsm_state5;
    static const sc_lv<31> ap_ST_fsm_state6;
    static const sc_lv<31> ap_ST_fsm_state7;
    static const sc_lv<31> ap_ST_fsm_state8;
    static const sc_lv<31> ap_ST_fsm_state9;
    static const sc_lv<31> ap_ST_fsm_state10;
    static const sc_lv<31> ap_ST_fsm_state11;
    static const sc_lv<31> ap_ST_fsm_state12;
    static const sc_lv<31> ap_ST_fsm_state13;
    static const sc_lv<31> ap_ST_fsm_state14;
    static const sc_lv<31> ap_ST_fsm_state15;
    static const sc_lv<31> ap_ST_fsm_state16;
    static const sc_lv<31> ap_ST_fsm_state17;
    static const sc_lv<31> ap_ST_fsm_state18;
    static const sc_lv<31> ap_ST_fsm_state19;
    static const sc_lv<31> ap_ST_fsm_state20;
    static const sc_lv<31> ap_ST_fsm_state21;
    static const sc_lv<31> ap_ST_fsm_state22;
    static const sc_lv<31> ap_ST_fsm_state23;
    static const sc_lv<31> ap_ST_fsm_state24;
    static const sc_lv<31> ap_ST_fsm_state25;
    static const sc_lv<31> ap_ST_fsm_state26;
    static const sc_lv<31> ap_ST_fsm_state27;
    static const sc_lv<31> ap_ST_fsm_state28;
    static const sc_lv<31> ap_ST_fsm_state29;
    static const sc_lv<31> ap_ST_fsm_state30;
    static const sc_lv<31> ap_ST_fsm_state31;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<14> ap_const_lv14_2000;
    static const sc_lv<14> ap_const_lv14_1FFF;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<9> ap_const_lv9_1A4;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<11> ap_const_lv11_1A4;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<11> ap_const_lv11_347;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<32> ap_const_lv32_53;
    static const sc_lv<24> ap_const_lv24_9C1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_acc_V_address0();
    void thread_acc_V_ce0();
    void thread_acc_V_d0();
    void thread_acc_V_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state27();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_brmerge8_fu_469_p2();
    void thread_data_V_address0();
    void thread_data_V_ce0();
    void thread_exitcond6_fu_270_p2();
    void thread_exitcond_fu_291_p2();
    void thread_extLd_fu_316_p1();
    void thread_grp_fu_334_ap_start();
    void thread_grp_fu_334_p1();
    void thread_grp_fu_528_p0();
    void thread_grp_fu_528_p00();
    void thread_grp_fu_528_p1();
    void thread_grp_product_fu_259_ap_start();
    void thread_iacc_3_fu_276_p2();
    void thread_im_3_fu_328_p2();
    void thread_in_index_3_fu_493_p2();
    void thread_ir_fu_297_p2();
    void thread_ires_3_fu_517_p2();
    void thread_lhs_V_fu_410_p1();
    void thread_out_index_3_fu_487_p2();
    void thread_out_index_cast_fu_313_p1();
    void thread_outidx_address0();
    void thread_outidx_ce0();
    void thread_overflow_fu_451_p2();
    void thread_p_Result_11_fu_437_p3();
    void thread_p_Result_s_fu_423_p3();
    void thread_p_Val2_19_fu_431_p2();
    void thread_p_s_fu_504_p3();
    void thread_p_shl8_fu_364_p3();
    void thread_res_V_address0();
    void thread_res_V_ce0();
    void thread_res_V_d0();
    void thread_res_V_we0();
    void thread_ret_V_fu_417_p2();
    void thread_rhs_V_fu_414_p1();
    void thread_tmp_20_fu_445_p2();
    void thread_tmp_23_fu_344_p1();
    void thread_tmp_59_fu_320_p3();
    void thread_tmp_61_fu_308_p1();
    void thread_tmp_62_fu_511_p2();
    void thread_tmp_63_fu_523_p1();
    void thread_tmp_64_fu_405_p1();
    void thread_tmp_65_fu_372_p3();
    void thread_tmp_66_fu_379_p1();
    void thread_tmp_67_fu_383_p2();
    void thread_tmp_68_fu_392_p1();
    void thread_tmp_69_fu_457_p2();
    void thread_tmp_70_fu_481_p2();
    void thread_tmp_71_fu_499_p2();
    void thread_tmp_72_fu_395_p2();
    void thread_tmp_73_fu_401_p1();
    void thread_tmp_8_fu_355_p4();
    void thread_tmp_fu_282_p1();
    void thread_tmp_s_fu_303_p1();
    void thread_underflow_fu_463_p2();
    void thread_w17_V_address0();
    void thread_w17_V_ce0();
    void thread_w17_V_load_cast_fu_389_p1();
    void thread_w_index_3_fu_475_p2();
    void thread_w_index_cast_fu_287_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
