// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pooling2d_cl_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pooling2d_cl_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pooling2d_cl_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state1 = "1";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state2 = "10";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state3 = "100";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state4 = "1000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state5 = "10000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state6 = "100000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state9 = "100000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<15> pooling2d_cl_1::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_1 = "1";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_2 = "10";
const sc_lv<1> pooling2d_cl_1::ap_const_lv1_1 = "1";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_3 = "11";
const sc_lv<1> pooling2d_cl_1::ap_const_lv1_0 = "0";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_4 = "100";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_5 = "101";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_6 = "110";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_7 = "111";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_8 = "1000";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_9 = "1001";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_B = "1011";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_C = "1100";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_D = "1101";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_E = "1110";
const sc_lv<5> pooling2d_cl_1::ap_const_lv5_0 = "00000";
const sc_lv<4> pooling2d_cl_1::ap_const_lv4_0 = "0000";
const sc_lv<2> pooling2d_cl_1::ap_const_lv2_0 = "00";
const sc_lv<32> pooling2d_cl_1::ap_const_lv32_A = "1010";
const sc_lv<3> pooling2d_cl_1::ap_const_lv3_1 = "1";
const sc_lv<64> pooling2d_cl_1::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<14> pooling2d_cl_1::ap_const_lv14_2000 = "10000000000000";
const sc_lv<5> pooling2d_cl_1::ap_const_lv5_10 = "10000";
const sc_lv<5> pooling2d_cl_1::ap_const_lv5_1 = "1";
const sc_lv<4> pooling2d_cl_1::ap_const_lv4_C = "1100";
const sc_lv<6> pooling2d_cl_1::ap_const_lv6_0 = "000000";
const sc_lv<4> pooling2d_cl_1::ap_const_lv4_2 = "10";
const sc_lv<2> pooling2d_cl_1::ap_const_lv2_2 = "10";
const sc_lv<2> pooling2d_cl_1::ap_const_lv2_1 = "1";
const sc_lv<4> pooling2d_cl_1::ap_const_lv4_B = "1011";
const sc_lv<12> pooling2d_cl_1::ap_const_lv12_D0 = "11010000";
const sc_lv<3> pooling2d_cl_1::ap_const_lv3_0 = "000";
const sc_lv<3> pooling2d_cl_1::ap_const_lv3_4 = "100";
const bool pooling2d_cl_1::ap_const_boolean_1 = true;

pooling2d_cl_1::pooling2d_cl_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    pool_V_U = new pooling2d_cl_pool_V("pool_V_U");
    pool_V_U->clk(ap_clk);
    pool_V_U->reset(ap_rst);
    pool_V_U->address0(pool_V_address0);
    pool_V_U->ce0(pool_V_ce0);
    pool_V_U->we0(pool_V_we0);
    pool_V_U->d0(pool_V_d0);
    pool_V_U->q0(pool_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_219_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_219_p2 );

    SC_METHOD(thread_data_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_20_fu_397_p1 );

    SC_METHOD(thread_data_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_exitcond_fu_219_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ff_reg_129 );

    SC_METHOD(thread_exitcond_i_i_fu_434_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( i_i_i_reg_199 );

    SC_METHOD(thread_extLd_fu_405_p1);
    sensitive << ( data_V_load_reg_563 );

    SC_METHOD(thread_ff_1_fu_225_p2);
    sensitive << ( ff_reg_129 );

    SC_METHOD(thread_ff_cast2_cast_fu_215_p1);
    sensitive << ( ff_reg_129 );

    SC_METHOD(thread_grp_fu_210_p2);
    sensitive << ( tmp_31_reg_521 );
    sensitive << ( ll_reg_177 );

    SC_METHOD(thread_i_fu_445_p2);
    sensitive << ( i_i_i_reg_199 );

    SC_METHOD(thread_ii_3_fu_291_p2);
    sensitive << ( ii_reg_141 );

    SC_METHOD(thread_jj_1_fu_451_p2);
    sensitive << ( jj_reg_153 );

    SC_METHOD(thread_kk_1_fu_307_p2);
    sensitive << ( kk_reg_165 );

    SC_METHOD(thread_kk_cast8_fu_297_p1);
    sensitive << ( kk_reg_165 );

    SC_METHOD(thread_ll_1_fu_349_p2);
    sensitive << ( ll_reg_177 );

    SC_METHOD(thread_ll_cast7_fu_339_p1);
    sensitive << ( ll_reg_177 );

    SC_METHOD(thread_p_shl5_cast_fu_257_p1);
    sensitive << ( p_shl5_fu_249_p3 );

    SC_METHOD(thread_p_shl5_fu_249_p3);
    sensitive << ( ii_reg_141 );

    SC_METHOD(thread_p_shl_cast_fu_245_p1);
    sensitive << ( p_shl_fu_237_p3 );

    SC_METHOD(thread_p_shl_fu_237_p3);
    sensitive << ( ii_reg_141 );

    SC_METHOD(thread_pool_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_15_fu_384_p1 );
    sensitive << ( tmp_17_fu_401_p1 );
    sensitive << ( tmp_i_i_fu_440_p1 );

    SC_METHOD(thread_pool_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_pool_V_d0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( extLd_fu_405_p1 );

    SC_METHOD(thread_pool_V_we0);
    sensitive << ( tmp_9_reg_517 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_13_fu_361_p2 );
    sensitive << ( tmp_13_reg_539 );
    sensitive << ( tmp_11_fu_343_p2 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_V_address0);
    sensitive << ( tmp_7_reg_568 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_res_V_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_res_V_d0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( agg_result_V_i_i_reg_188 );

    SC_METHOD(thread_res_V_we0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( exitcond_i_i_fu_434_p2 );

    SC_METHOD(thread_tmp1_cast_fu_389_p1);
    sensitive << ( tmp1_reg_548 );

    SC_METHOD(thread_tmp1_fu_379_p2);
    sensitive << ( ff_cast2_cast_reg_474 );
    sensitive << ( tmp_66_cast_cast_fu_375_p1 );

    SC_METHOD(thread_tmp_10_fu_333_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_10_fu_333_p10 );

    SC_METHOD(thread_tmp_10_fu_333_p10);
    sensitive << ( tmp_8_reg_511 );

    SC_METHOD(thread_tmp_10_fu_333_p2);
    sensitive << ( tmp_10_fu_333_p1 );

    SC_METHOD(thread_tmp_11_fu_343_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ll_reg_177 );

    SC_METHOD(thread_tmp_12_fu_355_p2);
    sensitive << ( jj_reg_153 );
    sensitive << ( ll_cast7_fu_339_p1 );

    SC_METHOD(thread_tmp_13_fu_361_p2);
    sensitive << ( tmp_9_reg_517 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_11_fu_343_p2 );
    sensitive << ( tmp_12_fu_355_p2 );

    SC_METHOD(thread_tmp_15_fu_384_p1);
    sensitive << ( grp_fu_210_p2 );

    SC_METHOD(thread_tmp_17_fu_401_p1);
    sensitive << ( tmp_16_reg_543 );

    SC_METHOD(thread_tmp_18_fu_367_p3);
    sensitive << ( tmp_12_fu_355_p2 );

    SC_METHOD(thread_tmp_19_fu_392_p2);
    sensitive << ( tmp_10_reg_526 );
    sensitive << ( tmp1_cast_fu_389_p1 );

    SC_METHOD(thread_tmp_1_fu_267_p4);
    sensitive << ( tmp_s_fu_261_p2 );

    SC_METHOD(thread_tmp_20_fu_397_p1);
    sensitive << ( tmp_19_reg_553 );

    SC_METHOD(thread_tmp_2_fu_277_p3);
    sensitive << ( ff_reg_129 );
    sensitive << ( tmp_1_fu_267_p4 );

    SC_METHOD(thread_tmp_31_fu_327_p2);
    sensitive << ( kk_reg_165 );

    SC_METHOD(thread_tmp_3_fu_285_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( jj_reg_153 );

    SC_METHOD(thread_tmp_4_fu_301_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( kk_reg_165 );

    SC_METHOD(thread_tmp_51_cast_fu_417_p1);
    sensitive << ( tmp_5_fu_409_p3 );

    SC_METHOD(thread_tmp_53_cast_fu_426_p1);
    sensitive << ( tmp_6_fu_421_p2 );

    SC_METHOD(thread_tmp_5_fu_409_p3);
    sensitive << ( jj_reg_153 );

    SC_METHOD(thread_tmp_66_cast_cast_fu_375_p1);
    sensitive << ( tmp_18_fu_367_p3 );

    SC_METHOD(thread_tmp_6_fu_421_p2);
    sensitive << ( tmp_2_reg_490 );
    sensitive << ( tmp_51_cast_fu_417_p1 );

    SC_METHOD(thread_tmp_7_fu_430_p1);
    sensitive << ( tmp_53_cast_fu_426_p1 );

    SC_METHOD(thread_tmp_8_fu_313_p2);
    sensitive << ( ii_reg_141 );
    sensitive << ( kk_cast8_fu_297_p1 );

    SC_METHOD(thread_tmp_9_fu_322_p2);
    sensitive << ( tmp_8_reg_511 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_fu_231_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ii_reg_141 );

    SC_METHOD(thread_tmp_i_i_37_fu_457_p2);
    sensitive << ( pool_V_load_reg_596 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( agg_result_V_i_i_reg_188 );

    SC_METHOD(thread_tmp_i_i_fu_440_p1);
    sensitive << ( i_i_i_reg_199 );

    SC_METHOD(thread_tmp_s_fu_261_p2);
    sensitive << ( p_shl_cast_fu_245_p1 );
    sensitive << ( p_shl5_cast_fu_257_p1 );

    SC_METHOD(thread_y_V_3_fu_462_p3);
    sensitive << ( pool_V_load_reg_596 );
    sensitive << ( agg_result_V_i_i_reg_188 );
    sensitive << ( tmp_i_i_37_fu_457_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_fu_231_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_3_fu_285_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_4_fu_301_p2 );
    sensitive << ( tmp_9_reg_517 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_13_fu_361_p2 );
    sensitive << ( tmp_11_fu_343_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( exitcond_i_i_fu_434_p2 );
    sensitive << ( exitcond_fu_219_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pooling2d_cl_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_address0, "(port)data_V_address0");
    sc_trace(mVcdFile, data_V_ce0, "(port)data_V_ce0");
    sc_trace(mVcdFile, data_V_q0, "(port)data_V_q0");
    sc_trace(mVcdFile, res_V_address0, "(port)res_V_address0");
    sc_trace(mVcdFile, res_V_ce0, "(port)res_V_ce0");
    sc_trace(mVcdFile, res_V_we0, "(port)res_V_we0");
    sc_trace(mVcdFile, res_V_d0, "(port)res_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ff_cast2_cast_fu_215_p1, "ff_cast2_cast_fu_215_p1");
    sc_trace(mVcdFile, ff_cast2_cast_reg_474, "ff_cast2_cast_reg_474");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ff_1_fu_225_p2, "ff_1_fu_225_p2");
    sc_trace(mVcdFile, ff_1_reg_482, "ff_1_reg_482");
    sc_trace(mVcdFile, tmp_2_fu_277_p3, "tmp_2_fu_277_p3");
    sc_trace(mVcdFile, tmp_2_reg_490, "tmp_2_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_fu_231_p2, "tmp_fu_231_p2");
    sc_trace(mVcdFile, ii_3_fu_291_p2, "ii_3_fu_291_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_3_fu_285_p2, "tmp_3_fu_285_p2");
    sc_trace(mVcdFile, kk_1_fu_307_p2, "kk_1_fu_307_p2");
    sc_trace(mVcdFile, kk_1_reg_506, "kk_1_reg_506");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_8_fu_313_p2, "tmp_8_fu_313_p2");
    sc_trace(mVcdFile, tmp_8_reg_511, "tmp_8_reg_511");
    sc_trace(mVcdFile, tmp_4_fu_301_p2, "tmp_4_fu_301_p2");
    sc_trace(mVcdFile, tmp_9_fu_322_p2, "tmp_9_fu_322_p2");
    sc_trace(mVcdFile, tmp_9_reg_517, "tmp_9_reg_517");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_31_fu_327_p2, "tmp_31_fu_327_p2");
    sc_trace(mVcdFile, tmp_31_reg_521, "tmp_31_reg_521");
    sc_trace(mVcdFile, tmp_10_fu_333_p2, "tmp_10_fu_333_p2");
    sc_trace(mVcdFile, tmp_10_reg_526, "tmp_10_reg_526");
    sc_trace(mVcdFile, ll_1_fu_349_p2, "ll_1_fu_349_p2");
    sc_trace(mVcdFile, ll_1_reg_534, "ll_1_reg_534");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_13_fu_361_p2, "tmp_13_fu_361_p2");
    sc_trace(mVcdFile, tmp_13_reg_539, "tmp_13_reg_539");
    sc_trace(mVcdFile, tmp_11_fu_343_p2, "tmp_11_fu_343_p2");
    sc_trace(mVcdFile, grp_fu_210_p2, "grp_fu_210_p2");
    sc_trace(mVcdFile, tmp_16_reg_543, "tmp_16_reg_543");
    sc_trace(mVcdFile, tmp1_fu_379_p2, "tmp1_fu_379_p2");
    sc_trace(mVcdFile, tmp1_reg_548, "tmp1_reg_548");
    sc_trace(mVcdFile, tmp_19_fu_392_p2, "tmp_19_fu_392_p2");
    sc_trace(mVcdFile, tmp_19_reg_553, "tmp_19_reg_553");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, data_V_load_reg_563, "data_V_load_reg_563");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_7_fu_430_p1, "tmp_7_fu_430_p1");
    sc_trace(mVcdFile, tmp_7_reg_568, "tmp_7_reg_568");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, pool_V_q0, "pool_V_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, exitcond_i_i_fu_434_p2, "exitcond_i_i_fu_434_p2");
    sc_trace(mVcdFile, i_fu_445_p2, "i_fu_445_p2");
    sc_trace(mVcdFile, i_reg_586, "i_reg_586");
    sc_trace(mVcdFile, jj_1_fu_451_p2, "jj_1_fu_451_p2");
    sc_trace(mVcdFile, pool_V_load_reg_596, "pool_V_load_reg_596");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, y_V_3_fu_462_p3, "y_V_3_fu_462_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, pool_V_address0, "pool_V_address0");
    sc_trace(mVcdFile, pool_V_ce0, "pool_V_ce0");
    sc_trace(mVcdFile, pool_V_we0, "pool_V_we0");
    sc_trace(mVcdFile, pool_V_d0, "pool_V_d0");
    sc_trace(mVcdFile, ff_reg_129, "ff_reg_129");
    sc_trace(mVcdFile, ii_reg_141, "ii_reg_141");
    sc_trace(mVcdFile, exitcond_fu_219_p2, "exitcond_fu_219_p2");
    sc_trace(mVcdFile, jj_reg_153, "jj_reg_153");
    sc_trace(mVcdFile, kk_reg_165, "kk_reg_165");
    sc_trace(mVcdFile, ll_reg_177, "ll_reg_177");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, agg_result_V_i_i_reg_188, "agg_result_V_i_i_reg_188");
    sc_trace(mVcdFile, i_i_i_reg_199, "i_i_i_reg_199");
    sc_trace(mVcdFile, tmp_15_fu_384_p1, "tmp_15_fu_384_p1");
    sc_trace(mVcdFile, tmp_20_fu_397_p1, "tmp_20_fu_397_p1");
    sc_trace(mVcdFile, tmp_17_fu_401_p1, "tmp_17_fu_401_p1");
    sc_trace(mVcdFile, tmp_i_i_fu_440_p1, "tmp_i_i_fu_440_p1");
    sc_trace(mVcdFile, extLd_fu_405_p1, "extLd_fu_405_p1");
    sc_trace(mVcdFile, p_shl_fu_237_p3, "p_shl_fu_237_p3");
    sc_trace(mVcdFile, p_shl5_fu_249_p3, "p_shl5_fu_249_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_245_p1, "p_shl_cast_fu_245_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_257_p1, "p_shl5_cast_fu_257_p1");
    sc_trace(mVcdFile, tmp_s_fu_261_p2, "tmp_s_fu_261_p2");
    sc_trace(mVcdFile, tmp_1_fu_267_p4, "tmp_1_fu_267_p4");
    sc_trace(mVcdFile, kk_cast8_fu_297_p1, "kk_cast8_fu_297_p1");
    sc_trace(mVcdFile, tmp_10_fu_333_p1, "tmp_10_fu_333_p1");
    sc_trace(mVcdFile, ll_cast7_fu_339_p1, "ll_cast7_fu_339_p1");
    sc_trace(mVcdFile, tmp_12_fu_355_p2, "tmp_12_fu_355_p2");
    sc_trace(mVcdFile, tmp_18_fu_367_p3, "tmp_18_fu_367_p3");
    sc_trace(mVcdFile, tmp_66_cast_cast_fu_375_p1, "tmp_66_cast_cast_fu_375_p1");
    sc_trace(mVcdFile, tmp1_cast_fu_389_p1, "tmp1_cast_fu_389_p1");
    sc_trace(mVcdFile, tmp_5_fu_409_p3, "tmp_5_fu_409_p3");
    sc_trace(mVcdFile, tmp_51_cast_fu_417_p1, "tmp_51_cast_fu_417_p1");
    sc_trace(mVcdFile, tmp_6_fu_421_p2, "tmp_6_fu_421_p2");
    sc_trace(mVcdFile, tmp_53_cast_fu_426_p1, "tmp_53_cast_fu_426_p1");
    sc_trace(mVcdFile, tmp_i_i_37_fu_457_p2, "tmp_i_i_37_fu_457_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp_10_fu_333_p10, "tmp_10_fu_333_p10");
#endif

    }
}

pooling2d_cl_1::~pooling2d_cl_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete pool_V_U;
}

void pooling2d_cl_1::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        agg_result_V_i_i_reg_188 = y_V_3_fu_462_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        agg_result_V_i_i_reg_188 = pool_V_q0.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_219_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_fu_231_p2.read(), ap_const_lv1_0))) {
        ff_reg_129 = ff_1_reg_482.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ff_reg_129 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_i_i_reg_199 = i_reg_586.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i_i_i_reg_199 = ap_const_lv3_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_219_p2.read()))) {
        ii_reg_141 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(tmp_3_fu_285_p2.read(), ap_const_lv1_0))) {
        ii_reg_141 = ii_3_fu_291_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_fu_231_p2.read(), ap_const_lv1_1))) {
        jj_reg_153 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_i_fu_434_p2.read()))) {
        jj_reg_153 = jj_1_fu_451_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_285_p2.read()))) {
        kk_reg_165 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_11_fu_343_p2.read()))) {
        kk_reg_165 = kk_1_reg_506.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ll_reg_177 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        ll_reg_177 = ll_1_reg_534.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        data_V_load_reg_563 = data_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ff_1_reg_482 = ff_1_fu_225_p2.read();
        ff_cast2_cast_reg_474 = ff_cast2_cast_fu_215_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_fu_434_p2.read()))) {
        i_reg_586 = i_fu_445_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        kk_1_reg_506 = kk_1_fu_307_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ll_1_reg_534 = ll_1_fu_349_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        pool_V_load_reg_596 = pool_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_343_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_517.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_361_p2.read()))) {
        tmp1_reg_548 = tmp1_fu_379_p2.read();
        tmp_16_reg_543 = grp_fu_210_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_10_reg_526 = tmp_10_fu_333_p2.read();
        tmp_31_reg_521 = tmp_31_fu_327_p2.read();
        tmp_9_reg_517 = tmp_9_fu_322_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_343_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_517.read()))) {
        tmp_13_reg_539 = tmp_13_fu_361_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_19_reg_553 = tmp_19_fu_392_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_fu_231_p2.read(), ap_const_lv1_1))) {
        tmp_2_reg_490 = tmp_2_fu_277_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_7_reg_568 = tmp_7_fu_430_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_301_p2.read()))) {
        tmp_8_reg_511 = tmp_8_fu_313_p2.read();
    }
}

void pooling2d_cl_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void pooling2d_cl_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void pooling2d_cl_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void pooling2d_cl_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_219_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void pooling2d_cl_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_219_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_data_V_address0() {
    data_V_address0 =  (sc_lv<12>) (tmp_20_fu_397_p1.read());
}

void pooling2d_cl_1::thread_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        data_V_ce0 = ap_const_logic_1;
    } else {
        data_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_exitcond_fu_219_p2() {
    exitcond_fu_219_p2 = (!ff_reg_129.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(ff_reg_129.read() == ap_const_lv5_10);
}

void pooling2d_cl_1::thread_exitcond_i_i_fu_434_p2() {
    exitcond_i_i_fu_434_p2 = (!i_i_i_reg_199.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_i_i_reg_199.read() == ap_const_lv3_4);
}

void pooling2d_cl_1::thread_extLd_fu_405_p1() {
    extLd_fu_405_p1 = esl_zext<14,13>(data_V_load_reg_563.read());
}

void pooling2d_cl_1::thread_ff_1_fu_225_p2() {
    ff_1_fu_225_p2 = (!ff_reg_129.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(ff_reg_129.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void pooling2d_cl_1::thread_ff_cast2_cast_fu_215_p1() {
    ff_cast2_cast_fu_215_p1 = esl_zext<9,5>(ff_reg_129.read());
}

void pooling2d_cl_1::thread_grp_fu_210_p2() {
    grp_fu_210_p2 = (!tmp_31_reg_521.read().is_01() || !ll_reg_177.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_31_reg_521.read()) + sc_biguint<2>(ll_reg_177.read()));
}

void pooling2d_cl_1::thread_i_fu_445_p2() {
    i_fu_445_p2 = (!i_i_i_reg_199.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i_i_reg_199.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pooling2d_cl_1::thread_ii_3_fu_291_p2() {
    ii_3_fu_291_p2 = (!ii_reg_141.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(ii_reg_141.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void pooling2d_cl_1::thread_jj_1_fu_451_p2() {
    jj_1_fu_451_p2 = (!jj_reg_153.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(jj_reg_153.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void pooling2d_cl_1::thread_kk_1_fu_307_p2() {
    kk_1_fu_307_p2 = (!kk_reg_165.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(kk_reg_165.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void pooling2d_cl_1::thread_kk_cast8_fu_297_p1() {
    kk_cast8_fu_297_p1 = esl_zext<4,2>(kk_reg_165.read());
}

void pooling2d_cl_1::thread_ll_1_fu_349_p2() {
    ll_1_fu_349_p2 = (!ll_reg_177.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ll_reg_177.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void pooling2d_cl_1::thread_ll_cast7_fu_339_p1() {
    ll_cast7_fu_339_p1 = esl_zext<4,2>(ll_reg_177.read());
}

void pooling2d_cl_1::thread_p_shl5_cast_fu_257_p1() {
    p_shl5_cast_fu_257_p1 = esl_zext<11,8>(p_shl5_fu_249_p3.read());
}

void pooling2d_cl_1::thread_p_shl5_fu_249_p3() {
    p_shl5_fu_249_p3 = esl_concat<4,4>(ii_reg_141.read(), ap_const_lv4_0);
}

void pooling2d_cl_1::thread_p_shl_cast_fu_245_p1() {
    p_shl_cast_fu_245_p1 = esl_zext<11,10>(p_shl_fu_237_p3.read());
}

void pooling2d_cl_1::thread_p_shl_fu_237_p3() {
    p_shl_fu_237_p3 = esl_concat<4,6>(ii_reg_141.read(), ap_const_lv6_0);
}

void pooling2d_cl_1::thread_pool_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        pool_V_address0 =  (sc_lv<2>) (tmp_i_i_fu_440_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        pool_V_address0 =  (sc_lv<2>) (tmp_17_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        pool_V_address0 =  (sc_lv<2>) (tmp_15_fu_384_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        pool_V_address0 =  (sc_lv<2>) (ap_const_lv64_0);
    } else {
        pool_V_address0 = "XX";
    }
}

void pooling2d_cl_1::thread_pool_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        pool_V_ce0 = ap_const_logic_1;
    } else {
        pool_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_pool_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        pool_V_d0 = extLd_fu_405_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        pool_V_d0 = ap_const_lv14_2000;
    } else {
        pool_V_d0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void pooling2d_cl_1::thread_pool_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_343_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_fu_361_p2.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_343_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_reg_517.read())))) || 
         (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_517.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_reg_539.read())))) {
        pool_V_we0 = ap_const_logic_1;
    } else {
        pool_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_res_V_address0() {
    res_V_address0 =  (sc_lv<10>) (tmp_7_reg_568.read());
}

void pooling2d_cl_1::thread_res_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        res_V_ce0 = ap_const_logic_1;
    } else {
        res_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_res_V_d0() {
    res_V_d0 = agg_result_V_i_i_reg_188.read();
}

void pooling2d_cl_1::thread_res_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_i_fu_434_p2.read()))) {
        res_V_we0 = ap_const_logic_1;
    } else {
        res_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_cl_1::thread_tmp1_cast_fu_389_p1() {
    tmp1_cast_fu_389_p1 = esl_zext<12,9>(tmp1_reg_548.read());
}

void pooling2d_cl_1::thread_tmp1_fu_379_p2() {
    tmp1_fu_379_p2 = (!ff_cast2_cast_reg_474.read().is_01() || !tmp_66_cast_cast_fu_375_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ff_cast2_cast_reg_474.read()) + sc_biguint<9>(tmp_66_cast_cast_fu_375_p1.read()));
}

void pooling2d_cl_1::thread_tmp_10_fu_333_p1() {
    tmp_10_fu_333_p1 =  (sc_lv<4>) (tmp_10_fu_333_p10.read());
}

void pooling2d_cl_1::thread_tmp_10_fu_333_p10() {
    tmp_10_fu_333_p10 = esl_zext<12,4>(tmp_8_reg_511.read());
}

void pooling2d_cl_1::thread_tmp_10_fu_333_p2() {
    tmp_10_fu_333_p2 = (!ap_const_lv12_D0.is_01() || !tmp_10_fu_333_p1.read().is_01())? sc_lv<12>(): sc_biguint<12>(ap_const_lv12_D0) * sc_biguint<4>(tmp_10_fu_333_p1.read());
}

void pooling2d_cl_1::thread_tmp_11_fu_343_p2() {
    tmp_11_fu_343_p2 = (!ll_reg_177.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(ll_reg_177.read() == ap_const_lv2_2);
}

void pooling2d_cl_1::thread_tmp_12_fu_355_p2() {
    tmp_12_fu_355_p2 = (!jj_reg_153.read().is_01() || !ll_cast7_fu_339_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(jj_reg_153.read()) + sc_biguint<4>(ll_cast7_fu_339_p1.read()));
}

void pooling2d_cl_1::thread_tmp_13_fu_361_p2() {
    tmp_13_fu_361_p2 = (!tmp_12_fu_355_p2.read().is_01() || !ap_const_lv4_B.is_01())? sc_lv<1>(): (sc_biguint<4>(tmp_12_fu_355_p2.read()) > sc_biguint<4>(ap_const_lv4_B));
}

void pooling2d_cl_1::thread_tmp_15_fu_384_p1() {
    tmp_15_fu_384_p1 = esl_zext<64,2>(grp_fu_210_p2.read());
}

void pooling2d_cl_1::thread_tmp_17_fu_401_p1() {
    tmp_17_fu_401_p1 = esl_zext<64,2>(tmp_16_reg_543.read());
}

void pooling2d_cl_1::thread_tmp_18_fu_367_p3() {
    tmp_18_fu_367_p3 = esl_concat<4,4>(tmp_12_fu_355_p2.read(), ap_const_lv4_0);
}

void pooling2d_cl_1::thread_tmp_19_fu_392_p2() {
    tmp_19_fu_392_p2 = (!tmp_10_reg_526.read().is_01() || !tmp1_cast_fu_389_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_10_reg_526.read()) + sc_biguint<12>(tmp1_cast_fu_389_p1.read()));
}

void pooling2d_cl_1::thread_tmp_1_fu_267_p4() {
    tmp_1_fu_267_p4 = tmp_s_fu_261_p2.read().range(10, 5);
}

void pooling2d_cl_1::thread_tmp_20_fu_397_p1() {
    tmp_20_fu_397_p1 = esl_zext<64,12>(tmp_19_reg_553.read());
}

void pooling2d_cl_1::thread_tmp_2_fu_277_p3() {
    tmp_2_fu_277_p3 = esl_concat<6,5>(tmp_1_fu_267_p4.read(), ff_reg_129.read());
}

void pooling2d_cl_1::thread_tmp_31_fu_327_p2() {
    tmp_31_fu_327_p2 = (!ap_const_lv2_1.is_01())? sc_lv<2>(): kk_reg_165.read() << (unsigned short)ap_const_lv2_1.to_uint();
}

void pooling2d_cl_1::thread_tmp_3_fu_285_p2() {
    tmp_3_fu_285_p2 = (!jj_reg_153.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): (sc_biguint<4>(jj_reg_153.read()) < sc_biguint<4>(ap_const_lv4_C));
}

void pooling2d_cl_1::thread_tmp_4_fu_301_p2() {
    tmp_4_fu_301_p2 = (!kk_reg_165.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(kk_reg_165.read() == ap_const_lv2_2);
}

void pooling2d_cl_1::thread_tmp_51_cast_fu_417_p1() {
    tmp_51_cast_fu_417_p1 = esl_zext<11,7>(tmp_5_fu_409_p3.read());
}

void pooling2d_cl_1::thread_tmp_53_cast_fu_426_p1() {
    tmp_53_cast_fu_426_p1 = esl_sext<32,11>(tmp_6_fu_421_p2.read());
}

void pooling2d_cl_1::thread_tmp_5_fu_409_p3() {
    tmp_5_fu_409_p3 = esl_concat<4,3>(jj_reg_153.read(), ap_const_lv3_0);
}

void pooling2d_cl_1::thread_tmp_66_cast_cast_fu_375_p1() {
    tmp_66_cast_cast_fu_375_p1 = esl_zext<9,8>(tmp_18_fu_367_p3.read());
}

void pooling2d_cl_1::thread_tmp_6_fu_421_p2() {
    tmp_6_fu_421_p2 = (!tmp_51_cast_fu_417_p1.read().is_01() || !tmp_2_reg_490.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_51_cast_fu_417_p1.read()) + sc_biguint<11>(tmp_2_reg_490.read()));
}

void pooling2d_cl_1::thread_tmp_7_fu_430_p1() {
    tmp_7_fu_430_p1 = esl_zext<64,32>(tmp_53_cast_fu_426_p1.read());
}

void pooling2d_cl_1::thread_tmp_8_fu_313_p2() {
    tmp_8_fu_313_p2 = (!ii_reg_141.read().is_01() || !kk_cast8_fu_297_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ii_reg_141.read()) + sc_biguint<4>(kk_cast8_fu_297_p1.read()));
}

void pooling2d_cl_1::thread_tmp_9_fu_322_p2() {
    tmp_9_fu_322_p2 = (!tmp_8_reg_511.read().is_01() || !ap_const_lv4_B.is_01())? sc_lv<1>(): (sc_biguint<4>(tmp_8_reg_511.read()) > sc_biguint<4>(ap_const_lv4_B));
}

void pooling2d_cl_1::thread_tmp_fu_231_p2() {
    tmp_fu_231_p2 = (!ii_reg_141.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): (sc_biguint<4>(ii_reg_141.read()) < sc_biguint<4>(ap_const_lv4_C));
}

void pooling2d_cl_1::thread_tmp_i_i_37_fu_457_p2() {
    tmp_i_i_37_fu_457_p2 = (!pool_V_load_reg_596.read().is_01() || !agg_result_V_i_i_reg_188.read().is_01())? sc_lv<1>(): (sc_bigint<14>(pool_V_load_reg_596.read()) > sc_bigint<14>(agg_result_V_i_i_reg_188.read()));
}

void pooling2d_cl_1::thread_tmp_i_i_fu_440_p1() {
    tmp_i_i_fu_440_p1 = esl_zext<64,3>(i_i_i_reg_199.read());
}

void pooling2d_cl_1::thread_tmp_s_fu_261_p2() {
    tmp_s_fu_261_p2 = (!p_shl_cast_fu_245_p1.read().is_01() || !p_shl5_cast_fu_257_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_245_p1.read()) - sc_biguint<11>(p_shl5_cast_fu_257_p1.read()));
}

void pooling2d_cl_1::thread_y_V_3_fu_462_p3() {
    y_V_3_fu_462_p3 = (!tmp_i_i_37_fu_457_p2.read()[0].is_01())? sc_lv<14>(): ((tmp_i_i_37_fu_457_p2.read()[0].to_bool())? pool_V_load_reg_596.read(): agg_result_V_i_i_reg_188.read());
}

void pooling2d_cl_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_219_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_fu_231_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_3_fu_285_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_301_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_11_fu_343_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_343_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_fu_361_p2.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_343_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_reg_517.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_i_fu_434_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

